
//	------------------------
//	Save as a TTX XML
//	------------------------

	function triggerTTXFileDownload(){

		var link = document.createElement('a');
		link.href = 'data:text/plain,' + generateTTXXML();
		var d = new Date();
		var yr = d.getFullYear();
		var mo = d.getMonth()+1;
		var day = d.getDate();
		var hr = d.getHours();
		var min = (d.getMinutes()<10? "0" : "") + d.getMinutes();
		var sec = (d.getSeconds()<10? "0" : "") + d.getSeconds();
		
		link.download = "TTX Data - " + _G.fontsettings.familyname + " - " +yr+"."+mo+"."+day+"-"+hr+"."+min+"."+sec+".ttx";
		link.click();
	}

	function generateTTXXML(){
		var con = '<?xml version="1.0" encoding="ISO-8859-1"?>';
		con += '<ttFont sfntVersion="OTTO" ttLibVersion="2.3">';
		con += genTable_glyphorder({});
		con += genTable_head({});
		con += genTable_hhea({});
		con += genTable_maxp({});
		con += genTable_os_2({});
		con += genTable_name({});
		con += genTable_cmap({});
		con += genTable_post({});
		con += genTable_cff({});
		con += genTable_hmtx({});
		con += '</ttFont>';

		return con;
	}

	var charstringnames = [".notdef","space","exclam","quotedbl","numbersign","ampersand","dollar","percent","quoteright","parenleft","parenright","asterisk","plus","comma","hyphen","period","slash","zero","one","two","three","four","five","six","seven","eight","nine","colon","semicolon","less","equal","greater","question","at","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","bracketleft","backslash","bracketright","asciicircum","underscore","quoteleft","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","braceleft","bar","braceright","asciitilde","exclamdown","cent","sterling","fraction","yen","florin","section","currency","quotesingle","quotedblleft","guillemotleft","guilsinglleft","guilsinglright","fi","fl","endash","dagger","daggerdbl","periodcentered","paragraph","bullet","quotesinglbase","quotedblbase","quotedblright","guillemotright","ellipsis","perthousand","questiondown","grave","acute","circumflex","tilde","macron","breve","dotaccent","dieresis","ring","cedilla","hungarumlaut","ogonek","caron","emdash","AE","ordfeminine","Lslash","Oslash","OE","ordmasculine","ae","dotlessi","lslash","oslash","oe","germandbls","onesuperior","logicalnot","mu","trademark","Eth","onehalf","plusminus","Thorn","onequarter","divide","brokenbar","degree","thorn","threequarters","twosuperior","registered","minus","eth","multiply","threesuperior","copyright","Aacute","Acircumflex","Adieresis","Agrave","Aring","Atilde","Ccedilla","Eacute","Ecircumflex","Edieresis","Egrave","Iacute","Icircumflex","Idieresis","Igrave","Ntilde","Oacute","Ocircumflex","Odieresis","Ograve","Otilde","Scaron","Uacute","Ucircumflex","Udieresis","Ugrave","Yacute","Ydieresis","Zcaron","aacute","acircumflex","adieresis","agrave","aring","atilde","ccedilla","eacute","ecircumflex","edieresis","egrave","iacute","icircumflex","idieresis","igrave","ntilde","oacute","ocircumflex","odieresis","ograve","otilde","scaron","uacute","ucircumflex","udieresis","ugrave","yacute","ydieresis","zcaron","f_i","Omega","pi","Euro","estimated","partialdiff","product","summation","uni2219","radical","infinity","integral","approxequal","notequal","lessequal","greaterequal","lozenge","uni02C9","uni00AD","uni03A9","uni00A0","afii61289","uni03BC","uni2215","f_l","a.superior","o.superior","one.superior","two.superior","three.superior","uni2206","uni2010"];	

	function genCharStringsPostScript(){
		var con = '';

		for(var cs=0; cs<charstringnames.length; cs++){
			con += '<CharString name="' + charstringnames[cs] + '">';
			if(cs==53){
				// int for char width
				// 
				con += 'rmoveto ';
				con += '1000 vlineto ';
				con += '500 hlineto ';
				con += '-1000 vlineto ';
				con += '-500 hlineto ';
				//con += 'closepath ';
				con += '50 50 rmoveto ';
				con += '400 hlineto ';
				con += '900 vlineto ';
				con += '-400 hlineto ';
				con += '-900 vlineto ';
				//con += 'closepath ';
			}
			con += 'endchar';
			con += '</CharString>';
		}

		return con;
	}

	// TABLES
/*
	function genTable_glyphorder(oa){
		var con = '<GlyphOrder>';
		con += '<!-- The id attribute is only for humans; it is ignored when parsed. -->';
		con += '<GlyphID id="0" name=".notdef"/>';
		con += '<GlyphID id="1" name="space"/>';
		con += '<GlyphID id="2" name="exclam"/>';
		con += '<GlyphID id="3" name="quotedbl"/>';
		con += '<GlyphID id="4" name="numbersign"/>';
		con += '<GlyphID id="5" name="dollar"/>';
		con += '<GlyphID id="6" name="percent"/>';
		con += '<GlyphID id="7" name="ampersand"/>';
		con += '<GlyphID id="8" name="quoteright"/>';
		con += '<GlyphID id="9" name="parenleft"/>';
		con += '<GlyphID id="10" name="parenright"/>';
		con += '<GlyphID id="11" name="asterisk"/>';
		con += '<GlyphID id="12" name="plus"/>';
		con += '<GlyphID id="13" name="comma"/>';
		con += '<GlyphID id="14" name="hyphen"/>';
		con += '<GlyphID id="15" name="period"/>';
		con += '<GlyphID id="16" name="slash"/>';
		con += '<GlyphID id="17" name="zero"/>';
		con += '<GlyphID id="18" name="one"/>';
		con += '<GlyphID id="19" name="two"/>';
		con += '<GlyphID id="20" name="three"/>';
		con += '<GlyphID id="21" name="four"/>';
		con += '<GlyphID id="22" name="five"/>';
		con += '<GlyphID id="23" name="six"/>';
		con += '<GlyphID id="24" name="seven"/>';
		con += '<GlyphID id="25" name="eight"/>';
		con += '<GlyphID id="26" name="nine"/>';
		con += '<GlyphID id="27" name="colon"/>';
		con += '<GlyphID id="28" name="semicolon"/>';
		con += '<GlyphID id="29" name="less"/>';
		con += '<GlyphID id="30" name="equal"/>';
		con += '<GlyphID id="31" name="greater"/>';
		con += '<GlyphID id="32" name="question"/>';
		con += '<GlyphID id="33" name="at"/>';
		con += '<GlyphID id="34" name="A"/>';
		con += '<GlyphID id="35" name="B"/>';
		con += '<GlyphID id="36" name="C"/>';
		con += '<GlyphID id="37" name="D"/>';
		con += '<GlyphID id="38" name="E"/>';
		con += '<GlyphID id="39" name="F"/>';
		con += '<GlyphID id="40" name="G"/>';
		con += '<GlyphID id="41" name="H"/>';
		con += '<GlyphID id="42" name="I"/>';
		con += '<GlyphID id="43" name="J"/>';
		con += '<GlyphID id="44" name="K"/>';
		con += '<GlyphID id="45" name="L"/>';
		con += '<GlyphID id="46" name="M"/>';
		con += '<GlyphID id="47" name="N"/>';
		con += '<GlyphID id="48" name="O"/>';
		con += '<GlyphID id="49" name="P"/>';
		con += '<GlyphID id="50" name="Q"/>';
		con += '<GlyphID id="51" name="R"/>';
		con += '<GlyphID id="52" name="S"/>';
		con += '<GlyphID id="53" name="T"/>';
		con += '<GlyphID id="54" name="U"/>';
		con += '<GlyphID id="55" name="V"/>';
		con += '<GlyphID id="56" name="W"/>';
		con += '<GlyphID id="57" name="X"/>';
		con += '<GlyphID id="58" name="Y"/>';
		con += '<GlyphID id="59" name="Z"/>';
		con += '<GlyphID id="60" name="bracketleft"/>';
		con += '<GlyphID id="61" name="backslash"/>';
		con += '<GlyphID id="62" name="bracketright"/>';
		con += '<GlyphID id="63" name="asciicircum"/>';
		con += '<GlyphID id="64" name="underscore"/>';
		con += '<GlyphID id="65" name="quoteleft"/>';
		con += '<GlyphID id="66" name="a"/>';
		con += '<GlyphID id="67" name="b"/>';
		con += '<GlyphID id="68" name="c"/>';
		con += '<GlyphID id="69" name="d"/>';
		con += '<GlyphID id="70" name="e"/>';
		con += '<GlyphID id="71" name="f"/>';
		con += '<GlyphID id="72" name="g"/>';
		con += '<GlyphID id="73" name="h"/>';
		con += '<GlyphID id="74" name="i"/>';
		con += '<GlyphID id="75" name="j"/>';
		con += '<GlyphID id="76" name="k"/>';
		con += '<GlyphID id="77" name="l"/>';
		con += '<GlyphID id="78" name="m"/>';
		con += '<GlyphID id="79" name="n"/>';
		con += '<GlyphID id="80" name="o"/>';
		con += '<GlyphID id="81" name="p"/>';
		con += '<GlyphID id="82" name="q"/>';
		con += '<GlyphID id="83" name="r"/>';
		con += '<GlyphID id="84" name="s"/>';
		con += '<GlyphID id="85" name="t"/>';
		con += '<GlyphID id="86" name="u"/>';
		con += '<GlyphID id="87" name="v"/>';
		con += '<GlyphID id="88" name="w"/>';
		con += '<GlyphID id="89" name="x"/>';
		con += '<GlyphID id="90" name="y"/>';
		con += '<GlyphID id="91" name="z"/>';
		con += '<GlyphID id="92" name="braceleft"/>';
		con += '<GlyphID id="93" name="bar"/>';
		con += '<GlyphID id="94" name="braceright"/>';
		con += '<GlyphID id="95" name="asciitilde"/>';
		con += '<GlyphID id="96" name="exclamdown"/>';
		con += '<GlyphID id="97" name="cent"/>';
		con += '<GlyphID id="98" name="sterling"/>';
		con += '<GlyphID id="99" name="fraction"/>';
		con += '<GlyphID id="100" name="yen"/>';
		con += '<GlyphID id="101" name="florin"/>';
		con += '<GlyphID id="102" name="section"/>';
		con += '<GlyphID id="103" name="currency"/>';
		con += '<GlyphID id="104" name="quotesingle"/>';
		con += '<GlyphID id="105" name="quotedblleft"/>';
		con += '<GlyphID id="106" name="guillemotleft"/>';
		con += '<GlyphID id="107" name="guilsinglleft"/>';
		con += '<GlyphID id="108" name="guilsinglright"/>';
		con += '<GlyphID id="109" name="fi"/>';
		con += '<GlyphID id="110" name="fl"/>';
		con += '<GlyphID id="111" name="endash"/>';
		con += '<GlyphID id="112" name="dagger"/>';
		con += '<GlyphID id="113" name="daggerdbl"/>';
		con += '<GlyphID id="114" name="periodcentered"/>';
		con += '<GlyphID id="115" name="paragraph"/>';
		con += '<GlyphID id="116" name="bullet"/>';
		con += '<GlyphID id="117" name="quotesinglbase"/>';
		con += '<GlyphID id="118" name="quotedblbase"/>';
		con += '<GlyphID id="119" name="quotedblright"/>';
		con += '<GlyphID id="120" name="guillemotright"/>';
		con += '<GlyphID id="121" name="ellipsis"/>';
		con += '<GlyphID id="122" name="perthousand"/>';
		con += '<GlyphID id="123" name="questiondown"/>';
		con += '<GlyphID id="124" name="grave"/>';
		con += '<GlyphID id="125" name="acute"/>';
		con += '<GlyphID id="126" name="circumflex"/>';
		con += '<GlyphID id="127" name="tilde"/>';
		con += '<GlyphID id="128" name="macron"/>';
		con += '<GlyphID id="129" name="breve"/>';
		con += '<GlyphID id="130" name="dotaccent"/>';
		con += '<GlyphID id="131" name="dieresis"/>';
		con += '<GlyphID id="132" name="ring"/>';
		con += '<GlyphID id="133" name="cedilla"/>';
		con += '<GlyphID id="134" name="hungarumlaut"/>';
		con += '<GlyphID id="135" name="ogonek"/>';
		con += '<GlyphID id="136" name="caron"/>';
		con += '<GlyphID id="137" name="emdash"/>';
		con += '<GlyphID id="138" name="AE"/>';
		con += '<GlyphID id="139" name="ordfeminine"/>';
		con += '<GlyphID id="140" name="Lslash"/>';
		con += '<GlyphID id="141" name="Oslash"/>';
		con += '<GlyphID id="142" name="OE"/>';
		con += '<GlyphID id="143" name="ordmasculine"/>';
		con += '<GlyphID id="144" name="ae"/>';
		con += '<GlyphID id="145" name="dotlessi"/>';
		con += '<GlyphID id="146" name="lslash"/>';
		con += '<GlyphID id="147" name="oslash"/>';
		con += '<GlyphID id="148" name="oe"/>';
		con += '<GlyphID id="149" name="germandbls"/>';
		con += '<GlyphID id="150" name="onesuperior"/>';
		con += '<GlyphID id="151" name="logicalnot"/>';
		con += '<GlyphID id="152" name="mu"/>';
		con += '<GlyphID id="153" name="trademark"/>';
		con += '<GlyphID id="154" name="Eth"/>';
		con += '<GlyphID id="155" name="onehalf"/>';
		con += '<GlyphID id="156" name="plusminus"/>';
		con += '<GlyphID id="157" name="Thorn"/>';
		con += '<GlyphID id="158" name="onequarter"/>';
		con += '<GlyphID id="159" name="divide"/>';
		con += '<GlyphID id="160" name="brokenbar"/>';
		con += '<GlyphID id="161" name="degree"/>';
		con += '<GlyphID id="162" name="thorn"/>';
		con += '<GlyphID id="163" name="threequarters"/>';
		con += '<GlyphID id="164" name="twosuperior"/>';
		con += '<GlyphID id="165" name="registered"/>';
		con += '<GlyphID id="166" name="minus"/>';
		con += '<GlyphID id="167" name="eth"/>';
		con += '<GlyphID id="168" name="multiply"/>';
		con += '<GlyphID id="169" name="threesuperior"/>';
		con += '<GlyphID id="170" name="copyright"/>';
		con += '<GlyphID id="171" name="Aacute"/>';
		con += '<GlyphID id="172" name="Acircumflex"/>';
		con += '<GlyphID id="173" name="Adieresis"/>';
		con += '<GlyphID id="174" name="Agrave"/>';
		con += '<GlyphID id="175" name="Aring"/>';
		con += '<GlyphID id="176" name="Atilde"/>';
		con += '<GlyphID id="177" name="Ccedilla"/>';
		con += '<GlyphID id="178" name="Eacute"/>';
		con += '<GlyphID id="179" name="Ecircumflex"/>';
		con += '<GlyphID id="180" name="Edieresis"/>';
		con += '<GlyphID id="181" name="Egrave"/>';
		con += '<GlyphID id="182" name="Iacute"/>';
		con += '<GlyphID id="183" name="Icircumflex"/>';
		con += '<GlyphID id="184" name="Idieresis"/>';
		con += '<GlyphID id="185" name="Igrave"/>';
		con += '<GlyphID id="186" name="Ntilde"/>';
		con += '<GlyphID id="187" name="Oacute"/>';
		con += '<GlyphID id="188" name="Ocircumflex"/>';
		con += '<GlyphID id="189" name="Odieresis"/>';
		con += '<GlyphID id="190" name="Ograve"/>';
		con += '<GlyphID id="191" name="Otilde"/>';
		con += '<GlyphID id="192" name="Scaron"/>';
		con += '<GlyphID id="193" name="Uacute"/>';
		con += '<GlyphID id="194" name="Ucircumflex"/>';
		con += '<GlyphID id="195" name="Udieresis"/>';
		con += '<GlyphID id="196" name="Ugrave"/>';
		con += '<GlyphID id="197" name="Yacute"/>';
		con += '<GlyphID id="198" name="Ydieresis"/>';
		con += '<GlyphID id="199" name="Zcaron"/>';
		con += '<GlyphID id="200" name="aacute"/>';
		con += '<GlyphID id="201" name="acircumflex"/>';
		con += '<GlyphID id="202" name="adieresis"/>';
		con += '<GlyphID id="203" name="agrave"/>';
		con += '<GlyphID id="204" name="aring"/>';
		con += '<GlyphID id="205" name="atilde"/>';
		con += '<GlyphID id="206" name="ccedilla"/>';
		con += '<GlyphID id="207" name="eacute"/>';
		con += '<GlyphID id="208" name="ecircumflex"/>';
		con += '<GlyphID id="209" name="edieresis"/>';
		con += '<GlyphID id="210" name="egrave"/>';
		con += '<GlyphID id="211" name="iacute"/>';
		con += '<GlyphID id="212" name="icircumflex"/>';
		con += '<GlyphID id="213" name="idieresis"/>';
		con += '<GlyphID id="214" name="igrave"/>';
		con += '<GlyphID id="215" name="ntilde"/>';
		con += '<GlyphID id="216" name="oacute"/>';
		con += '<GlyphID id="217" name="ocircumflex"/>';
		con += '<GlyphID id="218" name="odieresis"/>';
		con += '<GlyphID id="219" name="ograve"/>';
		con += '<GlyphID id="220" name="otilde"/>';
		con += '<GlyphID id="221" name="scaron"/>';
		con += '<GlyphID id="222" name="uacute"/>';
		con += '<GlyphID id="223" name="ucircumflex"/>';
		con += '<GlyphID id="224" name="udieresis"/>';
		con += '<GlyphID id="225" name="ugrave"/>';
		con += '<GlyphID id="226" name="yacute"/>';
		con += '<GlyphID id="227" name="ydieresis"/>';
		con += '<GlyphID id="228" name="zcaron"/>';
		con += '<GlyphID id="229" name="f_i"/>';
		con += '<GlyphID id="230" name="Omega"/>';
		con += '<GlyphID id="231" name="pi"/>';
		con += '<GlyphID id="232" name="Euro"/>';
		con += '<GlyphID id="233" name="estimated"/>';
		con += '<GlyphID id="234" name="partialdiff"/>';
		con += '<GlyphID id="235" name="product"/>';
		con += '<GlyphID id="236" name="summation"/>';
		con += '<GlyphID id="237" name="uni2219"/>';
		con += '<GlyphID id="238" name="radical"/>';
		con += '<GlyphID id="239" name="infinity"/>';
		con += '<GlyphID id="240" name="integral"/>';
		con += '<GlyphID id="241" name="approxequal"/>';
		con += '<GlyphID id="242" name="notequal"/>';
		con += '<GlyphID id="243" name="lessequal"/>';
		con += '<GlyphID id="244" name="greaterequal"/>';
		con += '<GlyphID id="245" name="lozenge"/>';
		con += '<GlyphID id="246" name="uni02C9"/>';
		con += '<GlyphID id="247" name="uni00AD"/>';
		con += '<GlyphID id="248" name="uni03A9"/>';
		con += '<GlyphID id="249" name="uni00A0"/>';
		con += '<GlyphID id="250" name="afii61289"/>';
		con += '<GlyphID id="251" name="uni03BC"/>';
		con += '<GlyphID id="252" name="uni2215"/>';
		con += '<GlyphID id="253" name="f_l"/>';
		con += '<GlyphID id="254" name="a.superior"/>';
		con += '<GlyphID id="255" name="o.superior"/>';
		con += '<GlyphID id="256" name="one.superior"/>';
		con += '<GlyphID id="257" name="two.superior"/>';
		con += '<GlyphID id="258" name="three.superior"/>';
		con += '<GlyphID id="259" name="uni2206"/>';
		con += '<GlyphID id="260" name="uni2010"/>';
		
		con += '</GlyphOrder>';
		return con;
	}
*/

	function genTable_glyphorder(oa){
		var con = '<GlyphOrder>';

		for(var cs=0; cs<charstringnames.length; cs++){
			con += '<GlyphID name="' + charstringnames[cs] + '"/>';
		}

		con += '</GlyphOrder>';
		return con;
	}

	function genTable_head(oa){
		var con = '<head>';
		con += '<!-- Most of this table will be recalculated by the compiler -->';
		con += '<tableVersion value="1.0"/>';
		con += '<fontRevision value="2.04098510742"/>';
		con += '<checkSumAdjustment value="0xfd4639aa"/>';
		con += '<magicNumber value="0x5f0f3cf5"/>';
		con += '<flags value="00000000 00000011"/>';
		con += '<unitsPerEm value="1000"/>';
		con += '<created value="Tue Jul 28 19:44:19 2009"/>';
		con += '<modified value="Tue Jul 28 19:44:19 2009"/>';
		con += '<xMin value="-123"/>';
		con += '<yMin value="-315"/>';
		con += '<xMax value="1264"/>';
		con += '<yMax value="1101"/>';
		con += '<macStyle value="00000000 00000000"/>';
		con += '<lowestRecPPEM value="3"/>';
		con += '<fontDirectionHint value="2"/>';
		con += '<indexToLocFormat value="0"/>';
		con += '<glyphDataFormat value="0"/>';		
		
		con += '</head>';
		return con;
	}

	function genTable_hhea(oa){
		var con = '<hhea>';
		con += '<tableVersion value="1.0"/>';
		con += '<ascent value="853"/>';
		con += '<descent value="-147"/>';
		con += '<lineGap value="200"/>';
		con += '<advanceWidthMax value="1293"/>';
		con += '<minLeftSideBearing value="-123"/>';
		con += '<minRightSideBearing value="-124"/>';
		con += '<xMaxExtent value="1264"/>';
		con += '<caretSlopeRise value="1"/>';
		con += '<caretSlopeRun value="0"/>';
		con += '<caretOffset value="0"/>';
		con += '<reserved0 value="0"/>';
		con += '<reserved1 value="0"/>';
		con += '<reserved2 value="0"/>';
		con += '<reserved3 value="0"/>';
		con += '<metricDataFormat value="0"/>';
		con += '<numberOfHMetrics value="261"/>';		
		
		con += '</hhea>';
		return con;
	}

	function genTable_maxp(oa){
		var con = '<maxp>';
		con += '<tableVersion value="0x5000"/>';
		con += '<numGlyphs value="261"/>';

		con += '</maxp>';
		return con;
	}

	function genTable_os_2(oa){
		var con = '<OS_2>';
		con += '<version value="3"/>';
		con += '<xAvgCharWidth value="553"/>';
		con += '<usWeightClass value="500"/>';
		con += '<usWidthClass value="5"/>';
		con += '<fsType value="00000000 00001000"/>';
		con += '<ySubscriptXSize value="650"/>';
		con += '<ySubscriptYSize value="600"/>';
		con += '<ySubscriptXOffset value="0"/>';
		con += '<ySubscriptYOffset value="75"/>';
		con += '<ySuperscriptXSize value="650"/>';
		con += '<ySuperscriptYSize value="600"/>';
		con += '<ySuperscriptXOffset value="0"/>';
		con += '<ySuperscriptYOffset value="350"/>';
		con += '<yStrikeoutSize value="50"/>';
		con += '<yStrikeoutPosition value="384"/>';
		con += '<sFamilyClass value="0"/>';
		con += '<panose>';
			con += '<bFamilyType value="2"/>';
			con += '<bSerifStyle value="11"/>';
			con += '<bWeight value="8"/>';
			con += '<bProportion value="3"/>';
			con += '<bContrast value="4"/>';
			con += '<bStrokeVariation value="7"/>';
			con += '<bArmStyle value="9"/>';
			con += '<bLetterForm value="2"/>';
			con += '<bMidline value="2"/>';
			con += '<bXHeight value="4"/>';
		con += '</panose>';
		con += '<ulUnicodeRange1 value="00000000 00000000 00000000 00000011"/>';
		con += '<ulUnicodeRange2 value="00000000 00000000 00000000 00000000"/>';
		con += '<ulUnicodeRange3 value="00000000 00000000 00000000 00000000"/>';
		con += '<ulUnicodeRange4 value="00000000 00000000 00000000 00000000"/>';
		con += '<achVendID value="ADBE"/>';
		con += '<fsSelection value="00000000 00000000"/>';
		con += '<fsFirstCharIndex value="32"/>';
		con += '<fsLastCharIndex value="64258"/>';
		con += '<sTypoAscender value="853"/>';
		con += '<sTypoDescender value="-147"/>';
		con += '<sTypoLineGap value="200"/>';
		con += '<usWinAscent value="1101"/>';
		con += '<usWinDescent value="315"/>';
		con += '<ulCodePageRange1 value="00100000 00000000 00000000 00000001"/>';
		con += '<ulCodePageRange2 value="00000000 00000000 00000000 00000000"/>';
		con += '<sxHeight value="640"/>';
		con += '<sCapHeight value="832"/>';
		con += '<usDefaultChar value="0"/>';
		con += '<usBreakChar value="32"/>';
		con += '<usMaxContex value="4"/>';
		
		con += '</OS_2>';
		return con;
	}

	function genTable_name(oa){
		var md = _G.fontsettings;
		
		var con = '<name>';
		con += '   <namerecord nameID="0" platformID="1" platEncID="0" langID="0x0">'+md.copyright+'</namerecord>';
		con += '   <namerecord nameID="1" platformID="1" platEncID="0" langID="0x0">'+md.familyname+'</namerecord>';
		con += '   <namerecord nameID="2" platformID="1" platEncID="0" langID="0x0">'+md.subfamilyname+'</namerecord>';
		con += '   <namerecord nameID="3" platformID="1" platEncID="0" langID="0x0">'+(md.fullname+' ; '+md.version)+'</namerecord>';
		con += '   <namerecord nameID="4" platformID="1" platEncID="0" langID="0x0">'+md.fullname+'</namerecord>';
		con += '   <namerecord nameID="5" platformID="1" platEncID="0" langID="0x0">'+md.version+'</namerecord>';
		con += '   <namerecord nameID="6" platformID="1" platEncID="0" langID="0x0">'+md.fullname+'</namerecord>';
		con += '   <namerecord nameID="8" platformID="1" platEncID="0" langID="0x0">'+md.manufacturername+'</namerecord>'; 
		con += '   <namerecord nameID="9" platformID="1" platEncID="0" langID="0x0">'+md.designername+'</namerecord>';
		con += '   <namerecord nameID="10" platformID="1" platEncID="0" langID="0x0">'+md.description+'</namerecord>'; 
		con += '   <namerecord nameID="11" platformID="1" platEncID="0" langID="0x0">'+md.manufacturerurl+'</namerecord>';
		con += '   <namerecord nameID="12" platformID="1" platEncID="0" langID="0x0">'+md.designerurl+'</namerecord>'; 
		con += '   <namerecord nameID="13" platformID="1" platEncID="0" langID="0x0">'+md.licensedescription+'</namerecord>'; 
		con += '   <namerecord nameID="14" platformID="1" platEncID="0" langID="0x0">'+md.licenseurl+'</namerecord>';
		con += '   <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">'+md.copyright+'</namerecord>';
		con += '   <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">'+md.familyname+'</namerecord>';
		con += '   <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">'+md.subfamilyname+'</namerecord>';
		con += '   <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">'+(md.fullname+' ; '+md.version)+'</namerecord>';
		con += '   <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">'+md.fullname+'</namerecord>';
		con += '   <namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">'+md.version+'</namerecord>';
		con += '   <namerecord nameID="6" platformID="3" platEncID="1" langID="0x409">'+md.fullname+'</namerecord>';
		con += '   <namerecord nameID="8" platformID="3" platEncID="1" langID="0x409">'+md.manufacturername+'</namerecord>';
		con += '   <namerecord nameID="9" platformID="3" platEncID="1" langID="0x409">'+md.designername+'</namerecord>';
		con += '   <namerecord nameID="10" platformID="3" platEncID="1" langID="0x409">'+md.description+'</namerecord>'; 
		con += '   <namerecord nameID="11" platformID="3" platEncID="1" langID="0x409">'+md.manufacturerurl+'</namerecord>';
		con += '   <namerecord nameID="12" platformID="3" platEncID="1" langID="0x409">'+md.designerurl+'</namerecord>'; 
		con += '   <namerecord nameID="13" platformID="3" platEncID="1" langID="0x409">'+md.licensedescription+'</namerecord>'; 
		con += '   <namerecord nameID="14" platformID="3" platEncID="1" langID="0x409">'+md.licenseurl+'</namerecord>';
		con += '</name>';

		return con;
	}


	function genTable_cmap(oa){
		var con = '<cmap>';
		con += '<tableVersion version="0"/>';
		con += '<cmap_format_4 platformID="0" platEncID="3" language="0">';
			con += '<map code="0x20" name="space"/> ';
			con += '<map code="0x21" name="exclam"/> ';
			con += '<map code="0x22" name="quotedbl"/> ';
			con += '<map code="0x23" name="numbersign"/> ';
			con += '<map code="0x24" name="dollar"/> ';
			con += '<map code="0x25" name="percent"/> ';
			con += '<map code="0x26" name="ampersand"/> ';
			con += '<map code="0x27" name="quotesingle"/> ';
			con += '<map code="0x28" name="parenleft"/> ';
			con += '<map code="0x29" name="parenright"/> ';
			con += '<map code="0x2a" name="asterisk"/> ';
			con += '<map code="0x2b" name="plus"/> ';
			con += '<map code="0x2c" name="comma"/> ';
			con += '<map code="0x2d" name="hyphen"/> ';
			con += '<map code="0x2e" name="period"/> ';
			con += '<map code="0x2f" name="slash"/> ';
			con += '<map code="0x30" name="zero"/> ';
			con += '<map code="0x31" name="one"/> ';
			con += '<map code="0x32" name="two"/> ';
			con += '<map code="0x33" name="three"/> ';
			con += '<map code="0x34" name="four"/> ';
			con += '<map code="0x35" name="five"/> ';
			con += '<map code="0x36" name="six"/> ';
			con += '<map code="0x37" name="seven"/> ';
			con += '<map code="0x38" name="eight"/> ';
			con += '<map code="0x39" name="nine"/> ';
			con += '<map code="0x3a" name="colon"/> ';
			con += '<map code="0x3b" name="semicolon"/> ';
			con += '<map code="0x3c" name="less"/> ';
			con += '<map code="0x3d" name="equal"/> ';
			con += '<map code="0x3e" name="greater"/> ';
			con += '<map code="0x3f" name="question"/> ';
			con += '<map code="0x40" name="at"/> ';
			con += '<map code="0x41" name="A"/> ';
			con += '<map code="0x42" name="B"/> ';
			con += '<map code="0x43" name="C"/> ';
			con += '<map code="0x44" name="D"/> ';
			con += '<map code="0x45" name="E"/> ';
			con += '<map code="0x46" name="F"/> ';
			con += '<map code="0x47" name="G"/> ';
			con += '<map code="0x48" name="H"/> ';
			con += '<map code="0x49" name="I"/> ';
			con += '<map code="0x4a" name="J"/> ';
			con += '<map code="0x4b" name="K"/> ';
			con += '<map code="0x4c" name="L"/> ';
			con += '<map code="0x4d" name="M"/> ';
			con += '<map code="0x4e" name="N"/> ';
			con += '<map code="0x4f" name="O"/> ';
			con += '<map code="0x50" name="P"/> ';
			con += '<map code="0x51" name="Q"/> ';
			con += '<map code="0x52" name="R"/> ';
			con += '<map code="0x53" name="S"/> ';
			con += '<map code="0x54" name="T"/> ';
			con += '<map code="0x55" name="U"/> ';
			con += '<map code="0x56" name="V"/> ';
			con += '<map code="0x57" name="W"/> ';
			con += '<map code="0x58" name="X"/> ';
			con += '<map code="0x59" name="Y"/> ';
			con += '<map code="0x5a" name="Z"/> ';
			con += '<map code="0x5b" name="bracketleft"/> ';
			con += '<map code="0x5c" name="backslash"/> ';
			con += '<map code="0x5d" name="bracketright"/> ';
			con += '<map code="0x5e" name="asciicircum"/> ';
			con += '<map code="0x5f" name="underscore"/> ';
			con += '<map code="0x60" name="grave"/> ';
			con += '<map code="0x61" name="a"/> ';
			con += '<map code="0x62" name="b"/> ';
			con += '<map code="0x63" name="c"/> ';
			con += '<map code="0x64" name="d"/> ';
			con += '<map code="0x65" name="e"/> ';
			con += '<map code="0x66" name="f"/> ';
			con += '<map code="0x67" name="g"/> ';
			con += '<map code="0x68" name="h"/> ';
			con += '<map code="0x69" name="i"/> ';
			con += '<map code="0x6a" name="j"/> ';
			con += '<map code="0x6b" name="k"/> ';
			con += '<map code="0x6c" name="l"/> ';
			con += '<map code="0x6d" name="m"/> ';
			con += '<map code="0x6e" name="n"/> ';
			con += '<map code="0x6f" name="o"/> ';
			con += '<map code="0x70" name="p"/> ';
			con += '<map code="0x71" name="q"/> ';
			con += '<map code="0x72" name="r"/> ';
			con += '<map code="0x73" name="s"/> ';
			con += '<map code="0x74" name="t"/> ';
			con += '<map code="0x75" name="u"/> ';
			con += '<map code="0x76" name="v"/> ';
			con += '<map code="0x77" name="w"/> ';
			con += '<map code="0x78" name="x"/> ';
			con += '<map code="0x79" name="y"/> ';
			con += '<map code="0x7a" name="z"/> ';
			con += '<map code="0x7b" name="braceleft"/> ';
			con += '<map code="0x7c" name="bar"/> ';
			con += '<map code="0x7d" name="braceright"/> ';
			con += '<map code="0x7e" name="asciitilde"/> ';
			/*
			con += '<map code="0xa0" name="uni00A0"/> ';
			con += '<map code="0xa1" name="exclamdown"/> ';
			con += '<map code="0xa2" name="cent"/> ';
			con += '<map code="0xa3" name="sterling"/> ';
			con += '<map code="0xa4" name="currency"/> ';
			con += '<map code="0xa5" name="yen"/> ';
			con += '<map code="0xa6" name="brokenbar"/> ';
			con += '<map code="0xa7" name="section"/> ';
			con += '<map code="0xa8" name="dieresis"/> ';
			con += '<map code="0xa9" name="copyright"/> ';
			con += '<map code="0xaa" name="ordfeminine"/> ';
			con += '<map code="0xab" name="guillemotleft"/> ';
			con += '<map code="0xac" name="logicalnot"/> ';
			con += '<map code="0xad" name="uni00AD"/> ';
			con += '<map code="0xae" name="registered"/> ';
			con += '<map code="0xaf" name="macron"/> ';
			con += '<map code="0xb0" name="degree"/> ';
			con += '<map code="0xb1" name="plusminus"/> ';
			con += '<map code="0xb2" name="twosuperior"/> ';
			con += '<map code="0xb3" name="threesuperior"/> ';
			con += '<map code="0xb4" name="acute"/> ';
			con += '<map code="0xb5" name="mu"/> ';
			con += '<map code="0xb6" name="paragraph"/> ';
			con += '<map code="0xb7" name="periodcentered"/> ';
			con += '<map code="0xb8" name="cedilla"/> ';
			con += '<map code="0xb9" name="onesuperior"/> ';
			con += '<map code="0xba" name="ordmasculine"/> ';
			con += '<map code="0xbb" name="guillemotright"/> ';
			con += '<map code="0xbc" name="onequarter"/> ';
			con += '<map code="0xbd" name="onehalf"/> ';
			con += '<map code="0xbe" name="threequarters"/> ';
			con += '<map code="0xbf" name="questiondown"/> ';
			con += '<map code="0xc0" name="Agrave"/> ';
			con += '<map code="0xc1" name="Aacute"/> ';
			con += '<map code="0xc2" name="Acircumflex"/> ';
			con += '<map code="0xc3" name="Atilde"/> ';
			con += '<map code="0xc4" name="Adieresis"/> ';
			con += '<map code="0xc5" name="Aring"/> ';
			con += '<map code="0xc6" name="AE"/> ';
			con += '<map code="0xc7" name="Ccedilla"/> ';
			con += '<map code="0xc8" name="Egrave"/> ';
			con += '<map code="0xc9" name="Eacute"/> ';
			con += '<map code="0xca" name="Ecircumflex"/> ';
			con += '<map code="0xcb" name="Edieresis"/> ';
			con += '<map code="0xcc" name="Igrave"/> ';
			con += '<map code="0xcd" name="Iacute"/> ';
			con += '<map code="0xce" name="Icircumflex"/> ';
			con += '<map code="0xcf" name="Idieresis"/> ';
			con += '<map code="0xd0" name="Eth"/> ';
			con += '<map code="0xd1" name="Ntilde"/> ';
			con += '<map code="0xd2" name="Ograve"/> ';
			con += '<map code="0xd3" name="Oacute"/> ';
			con += '<map code="0xd4" name="Ocircumflex"/> ';
			con += '<map code="0xd5" name="Otilde"/> ';
			con += '<map code="0xd6" name="Odieresis"/> ';
			con += '<map code="0xd7" name="multiply"/> ';
			con += '<map code="0xd8" name="Oslash"/> ';
			con += '<map code="0xd9" name="Ugrave"/> ';
			con += '<map code="0xda" name="Uacute"/> ';
			con += '<map code="0xdb" name="Ucircumflex"/> ';
			con += '<map code="0xdc" name="Udieresis"/> ';
			con += '<map code="0xdd" name="Yacute"/> ';
			con += '<map code="0xde" name="Thorn"/> ';
			con += '<map code="0xdf" name="germandbls"/> ';
			con += '<map code="0xe0" name="agrave"/> ';
			con += '<map code="0xe1" name="aacute"/> ';
			con += '<map code="0xe2" name="acircumflex"/> ';
			con += '<map code="0xe3" name="atilde"/> ';
			con += '<map code="0xe4" name="adieresis"/> ';
			con += '<map code="0xe5" name="aring"/> ';
			con += '<map code="0xe6" name="ae"/> ';
			con += '<map code="0xe7" name="ccedilla"/> ';
			con += '<map code="0xe8" name="egrave"/> ';
			con += '<map code="0xe9" name="eacute"/> ';
			con += '<map code="0xea" name="ecircumflex"/> ';
			con += '<map code="0xeb" name="edieresis"/> ';
			con += '<map code="0xec" name="igrave"/> ';
			con += '<map code="0xed" name="iacute"/> ';
			con += '<map code="0xee" name="icircumflex"/> ';
			con += '<map code="0xef" name="idieresis"/> ';
			con += '<map code="0xf0" name="eth"/> ';
			con += '<map code="0xf1" name="ntilde"/> ';
			con += '<map code="0xf2" name="ograve"/> ';
			con += '<map code="0xf3" name="oacute"/> ';
			con += '<map code="0xf4" name="ocircumflex"/> ';
			con += '<map code="0xf5" name="otilde"/> ';
			con += '<map code="0xf6" name="odieresis"/> ';
			con += '<map code="0xf7" name="divide"/> ';
			con += '<map code="0xf8" name="oslash"/> ';
			con += '<map code="0xf9" name="ugrave"/> ';
			con += '<map code="0xfa" name="uacute"/> ';
			con += '<map code="0xfb" name="ucircumflex"/> ';
			con += '<map code="0xfc" name="udieresis"/> ';
			con += '<map code="0xfd" name="yacute"/> ';
			con += '<map code="0xfe" name="thorn"/> ';
			con += '<map code="0xff" name="ydieresis"/> ';
			con += '<map code="0x131" name="dotlessi"/> ';
			con += '<map code="0x141" name="Lslash"/> ';
			con += '<map code="0x142" name="lslash"/> ';
			con += '<map code="0x152" name="OE"/> ';
			con += '<map code="0x153" name="oe"/> ';
			con += '<map code="0x160" name="Scaron"/> ';
			con += '<map code="0x161" name="scaron"/> ';
			con += '<map code="0x178" name="Ydieresis"/> ';
			con += '<map code="0x17d" name="Zcaron"/> ';
			con += '<map code="0x17e" name="zcaron"/> ';
			con += '<map code="0x192" name="florin"/> ';
			con += '<map code="0x2c6" name="circumflex"/> ';
			con += '<map code="0x2c7" name="caron"/> ';
			con += '<map code="0x2c9" name="uni02C9"/> ';
			con += '<map code="0x2d8" name="breve"/> ';
			con += '<map code="0x2d9" name="dotaccent"/> ';
			con += '<map code="0x2da" name="ring"/> ';
			con += '<map code="0x2db" name="ogonek"/> ';
			con += '<map code="0x2dc" name="tilde"/> ';
			con += '<map code="0x2dd" name="hungarumlaut"/> ';
			con += '<map code="0x3a9" name="uni03A9"/> ';
			con += '<map code="0x3bc" name="uni03BC"/> ';
			con += '<map code="0x3c0" name="pi"/> ';
			con += '<map code="0x2010" name="uni2010"/> ';
			con += '<map code="0x2013" name="endash"/> ';
			con += '<map code="0x2014" name="emdash"/> ';
			con += '<map code="0x2018" name="quoteleft"/> ';
			con += '<map code="0x2019" name="quoteright"/> ';
			con += '<map code="0x201a" name="quotesinglbase"/> ';
			con += '<map code="0x201c" name="quotedblleft"/> ';
			con += '<map code="0x201d" name="quotedblright"/> ';
			con += '<map code="0x201e" name="quotedblbase"/> ';
			con += '<map code="0x2020" name="dagger"/> ';
			con += '<map code="0x2021" name="daggerdbl"/> ';
			con += '<map code="0x2022" name="bullet"/> ';
			con += '<map code="0x2026" name="ellipsis"/> ';
			con += '<map code="0x2030" name="perthousand"/> ';
			con += '<map code="0x2039" name="guilsinglleft"/> ';
			con += '<map code="0x203a" name="guilsinglright"/> ';
			con += '<map code="0x2044" name="fraction"/> ';
			con += '<map code="0x20ac" name="Euro"/> ';
			con += '<map code="0x2113" name="afii61289"/> ';
			con += '<map code="0x2122" name="trademark"/> ';
			con += '<map code="0x2126" name="Omega"/> ';
			con += '<map code="0x212e" name="estimated"/> ';
			con += '<map code="0x2202" name="partialdiff"/> ';
			con += '<map code="0x2206" name="uni2206"/> ';
			con += '<map code="0x220f" name="product"/> ';
			con += '<map code="0x2211" name="summation"/> ';
			con += '<map code="0x2212" name="minus"/> ';
			con += '<map code="0x2215" name="uni2215"/> ';
			con += '<map code="0x2219" name="uni2219"/> ';
			con += '<map code="0x221a" name="radical"/> ';
			con += '<map code="0x221e" name="infinity"/> ';
			con += '<map code="0x222b" name="integral"/> ';
			con += '<map code="0x2248" name="approxequal"/> ';
			con += '<map code="0x2260" name="notequal"/> ';
			con += '<map code="0x2264" name="lessequal"/> ';
			con += '<map code="0x2265" name="greaterequal"/> ';
			con += '<map code="0x25ca" name="lozenge"/> ';
			con += '<map code="0xfb01" name="fi"/> ';
			con += '<map code="0xfb02" name="fl"/> ';
			*/
		con += '</cmap_format_4>';
		con += '<cmap_format_6 platformID="1" platEncID="0" language="0">';
			con += '<map code="0x9" name="space"/>';
			con += '<map code="0xa" name=".notdef"/>';
			con += '<map code="0xb" name=".notdef"/>';
			con += '<map code="0xc" name=".notdef"/>';
			con += '<map code="0xd" name="space"/>';
			con += '<map code="0xe" name=".notdef"/>';
			con += '<map code="0xf" name=".notdef"/>';
			con += '<map code="0x10" name=".notdef"/>';
			con += '<map code="0x11" name=".notdef"/>';
			con += '<map code="0x12" name=".notdef"/>';
			con += '<map code="0x13" name=".notdef"/>';
			con += '<map code="0x14" name=".notdef"/>';
			con += '<map code="0x15" name=".notdef"/>';
			con += '<map code="0x16" name=".notdef"/>';
			con += '<map code="0x17" name=".notdef"/>';
			con += '<map code="0x18" name=".notdef"/>';
			con += '<map code="0x19" name=".notdef"/>';
			con += '<map code="0x1a" name=".notdef"/>';
			con += '<map code="0x1b" name=".notdef"/>';
			con += '<map code="0x1c" name=".notdef"/>';
			con += '<map code="0x1d" name=".notdef"/>';
			con += '<map code="0x1e" name=".notdef"/>';
			con += '<map code="0x1f" name=".notdef"/>';
			con += '<map code="0x20" name="space"/>';
			con += '<map code="0x21" name="exclam"/>';
			con += '<map code="0x22" name="quotedbl"/>';
			con += '<map code="0x23" name="numbersign"/>';
			con += '<map code="0x24" name="dollar"/>';
			con += '<map code="0x25" name="percent"/>';
			con += '<map code="0x26" name="ampersand"/>';
			con += '<map code="0x27" name="quotesingle"/>';
			con += '<map code="0x28" name="parenleft"/>';
			con += '<map code="0x29" name="parenright"/>';
			con += '<map code="0x2a" name="asterisk"/>';
			con += '<map code="0x2b" name="plus"/>';
			con += '<map code="0x2c" name="comma"/>';
			con += '<map code="0x2d" name="hyphen"/>';
			con += '<map code="0x2e" name="period"/>';
			con += '<map code="0x2f" name="slash"/>';
			con += '<map code="0x30" name="zero"/>';
			con += '<map code="0x31" name="one"/>';
			con += '<map code="0x32" name="two"/>';
			con += '<map code="0x33" name="three"/>';
			con += '<map code="0x34" name="four"/>';
			con += '<map code="0x35" name="five"/>';
			con += '<map code="0x36" name="six"/>';
			con += '<map code="0x37" name="seven"/>';
			con += '<map code="0x38" name="eight"/>';
			con += '<map code="0x39" name="nine"/>';
			con += '<map code="0x3a" name="colon"/>';
			con += '<map code="0x3b" name="semicolon"/>';
			con += '<map code="0x3c" name="less"/>';
			con += '<map code="0x3d" name="equal"/>';
			con += '<map code="0x3e" name="greater"/>';
			con += '<map code="0x3f" name="question"/>';
			con += '<map code="0x40" name="at"/>';
			con += '<map code="0x41" name="A"/>';
			con += '<map code="0x42" name="B"/>';
			con += '<map code="0x43" name="C"/>';
			con += '<map code="0x44" name="D"/>';
			con += '<map code="0x45" name="E"/>';
			con += '<map code="0x46" name="F"/>';
			con += '<map code="0x47" name="G"/>';
			con += '<map code="0x48" name="H"/>';
			con += '<map code="0x49" name="I"/>';
			con += '<map code="0x4a" name="J"/>';
			con += '<map code="0x4b" name="K"/>';
			con += '<map code="0x4c" name="L"/>';
			con += '<map code="0x4d" name="M"/>';
			con += '<map code="0x4e" name="N"/>';
			con += '<map code="0x4f" name="O"/>';
			con += '<map code="0x50" name="P"/>';
			con += '<map code="0x51" name="Q"/>';
			con += '<map code="0x52" name="R"/>';
			con += '<map code="0x53" name="S"/>';
			con += '<map code="0x54" name="T"/>';
			con += '<map code="0x55" name="U"/>';
			con += '<map code="0x56" name="V"/>';
			con += '<map code="0x57" name="W"/>';
			con += '<map code="0x58" name="X"/>';
			con += '<map code="0x59" name="Y"/>';
			con += '<map code="0x5a" name="Z"/>';
			con += '<map code="0x5b" name="bracketleft"/>';
			con += '<map code="0x5c" name="backslash"/>';
			con += '<map code="0x5d" name="bracketright"/>';
			con += '<map code="0x5e" name="asciicircum"/>';
			con += '<map code="0x5f" name="underscore"/>';
			con += '<map code="0x60" name="grave"/>';
			con += '<map code="0x61" name="a"/>';
			con += '<map code="0x62" name="b"/>';
			con += '<map code="0x63" name="c"/>';
			con += '<map code="0x64" name="d"/>';
			con += '<map code="0x65" name="e"/>';
			con += '<map code="0x66" name="f"/>';
			con += '<map code="0x67" name="g"/>';
			con += '<map code="0x68" name="h"/>';
			con += '<map code="0x69" name="i"/>';
			con += '<map code="0x6a" name="j"/>';
			con += '<map code="0x6b" name="k"/>';
			con += '<map code="0x6c" name="l"/>';
			con += '<map code="0x6d" name="m"/>';
			con += '<map code="0x6e" name="n"/>';
			con += '<map code="0x6f" name="o"/>';
			con += '<map code="0x70" name="p"/>';
			con += '<map code="0x71" name="q"/>';
			con += '<map code="0x72" name="r"/>';
			con += '<map code="0x73" name="s"/>';
			con += '<map code="0x74" name="t"/>';
			con += '<map code="0x75" name="u"/>';
			con += '<map code="0x76" name="v"/>';
			con += '<map code="0x77" name="w"/>';
			con += '<map code="0x78" name="x"/>';
			con += '<map code="0x79" name="y"/>';
			con += '<map code="0x7a" name="z"/>';
			con += '<map code="0x7b" name="braceleft"/>';
			con += '<map code="0x7c" name="bar"/>';
			con += '<map code="0x7d" name="braceright"/>';
			con += '<map code="0x7e" name="asciitilde"/>';
			/*
			con += '<map code="0x7f" name=".notdef"/>';
			con += '<map code="0x80" name="Adieresis"/>';
			con += '<map code="0x81" name="Aring"/>';
			con += '<map code="0x82" name="Ccedilla"/>';
			con += '<map code="0x83" name="Eacute"/>';
			con += '<map code="0x84" name="Ntilde"/>';
			con += '<map code="0x85" name="Odieresis"/>';
			con += '<map code="0x86" name="Udieresis"/>';
			con += '<map code="0x87" name="aacute"/>';
			con += '<map code="0x88" name="agrave"/>';
			con += '<map code="0x89" name="acircumflex"/>';
			con += '<map code="0x8a" name="adieresis"/>';
			con += '<map code="0x8b" name="atilde"/>';
			con += '<map code="0x8c" name="aring"/>';
			con += '<map code="0x8d" name="ccedilla"/>';
			con += '<map code="0x8e" name="eacute"/>';
			con += '<map code="0x8f" name="egrave"/>';
			con += '<map code="0x90" name="ecircumflex"/>';
			con += '<map code="0x91" name="edieresis"/>';
			con += '<map code="0x92" name="iacute"/>';
			con += '<map code="0x93" name="igrave"/>';
			con += '<map code="0x94" name="icircumflex"/>';
			con += '<map code="0x95" name="idieresis"/>';
			con += '<map code="0x96" name="ntilde"/>';
			con += '<map code="0x97" name="oacute"/>';
			con += '<map code="0x98" name="ograve"/>';
			con += '<map code="0x99" name="ocircumflex"/>';
			con += '<map code="0x9a" name="odieresis"/>';
			con += '<map code="0x9b" name="otilde"/>';
			con += '<map code="0x9c" name="uacute"/>';
			con += '<map code="0x9d" name="ugrave"/>';
			con += '<map code="0x9e" name="ucircumflex"/>';
			con += '<map code="0x9f" name="udieresis"/>';
			con += '<map code="0xa0" name="dagger"/>';
			con += '<map code="0xa1" name="degree"/>';
			con += '<map code="0xa2" name="cent"/>';
			con += '<map code="0xa3" name="sterling"/>';
			con += '<map code="0xa4" name="section"/>';
			con += '<map code="0xa5" name="bullet"/>';
			con += '<map code="0xa6" name="paragraph"/>';
			con += '<map code="0xa7" name="germandbls"/>';
			con += '<map code="0xa8" name="registered"/>';
			con += '<map code="0xa9" name="copyright"/>';
			con += '<map code="0xaa" name="trademark"/>';
			con += '<map code="0xab" name="acute"/>';
			con += '<map code="0xac" name="dieresis"/>';
			con += '<map code="0xad" name="notequal"/>';
			con += '<map code="0xae" name="AE"/>';
			con += '<map code="0xaf" name="Oslash"/>';
			con += '<map code="0xb0" name="infinity"/>';
			con += '<map code="0xb1" name="plusminus"/>';
			con += '<map code="0xb2" name="lessequal"/>';
			con += '<map code="0xb3" name="greaterequal"/>';
			con += '<map code="0xb4" name="yen"/>';
			con += '<map code="0xb5" name="mu"/>';
			con += '<map code="0xb6" name="partialdiff"/>';
			con += '<map code="0xb7" name="summation"/>';
			con += '<map code="0xb8" name="product"/>';
			con += '<map code="0xb9" name="pi"/>';
			con += '<map code="0xba" name="integral"/>';
			con += '<map code="0xbb" name="ordfeminine"/>';
			con += '<map code="0xbc" name="ordmasculine"/>';
			con += '<map code="0xbd" name="uni03A9"/>';
			con += '<map code="0xbe" name="ae"/>';
			con += '<map code="0xbf" name="oslash"/>';
			con += '<map code="0xc0" name="questiondown"/>';
			con += '<map code="0xc1" name="exclamdown"/>';
			con += '<map code="0xc2" name="logicalnot"/>';
			con += '<map code="0xc3" name="radical"/>';
			con += '<map code="0xc4" name="florin"/>';
			con += '<map code="0xc5" name="approxequal"/>';
			con += '<map code="0xc6" name="uni2206"/>';
			con += '<map code="0xc7" name="guillemotleft"/>';
			con += '<map code="0xc8" name="guillemotright"/>';
			con += '<map code="0xc9" name="ellipsis"/>';
			con += '<map code="0xca" name="uni00A0"/>';
			con += '<map code="0xcb" name="Agrave"/>';
			con += '<map code="0xcc" name="Atilde"/>';
			con += '<map code="0xcd" name="Otilde"/>';
			con += '<map code="0xce" name="OE"/>';
			con += '<map code="0xcf" name="oe"/>';
			con += '<map code="0xd0" name="endash"/>';
			con += '<map code="0xd1" name="emdash"/>';
			con += '<map code="0xd2" name="quotedblleft"/>';
			con += '<map code="0xd3" name="quotedblright"/>';
			con += '<map code="0xd4" name="quoteleft"/>';
			con += '<map code="0xd5" name="quoteright"/>';
			con += '<map code="0xd6" name="divide"/>';
			con += '<map code="0xd7" name="lozenge"/>';
			con += '<map code="0xd8" name="ydieresis"/>';
			con += '<map code="0xd9" name="Ydieresis"/>';
			con += '<map code="0xda" name="fraction"/>';
			con += '<map code="0xdb" name="Euro"/>';
			con += '<map code="0xdc" name="guilsinglleft"/>';
			con += '<map code="0xdd" name="guilsinglright"/>';
			con += '<map code="0xde" name="fi"/>';
			con += '<map code="0xdf" name="fl"/>';
			con += '<map code="0xe0" name="daggerdbl"/>';
			con += '<map code="0xe1" name="periodcentered"/>';
			con += '<map code="0xe2" name="quotesinglbase"/>';
			con += '<map code="0xe3" name="quotedblbase"/>';
			con += '<map code="0xe4" name="perthousand"/>';
			con += '<map code="0xe5" name="Acircumflex"/>';
			con += '<map code="0xe6" name="Ecircumflex"/>';
			con += '<map code="0xe7" name="Aacute"/>';
			con += '<map code="0xe8" name="Edieresis"/>';
			con += '<map code="0xe9" name="Egrave"/>';
			con += '<map code="0xea" name="Iacute"/>';
			con += '<map code="0xeb" name="Icircumflex"/>';
			con += '<map code="0xec" name="Idieresis"/>';
			con += '<map code="0xed" name="Igrave"/>';
			con += '<map code="0xee" name="Oacute"/>';
			con += '<map code="0xef" name="Ocircumflex"/>';
			con += '<map code="0xf0" name=".notdef"/>';
			con += '<map code="0xf1" name="Ograve"/>';
			con += '<map code="0xf2" name="Uacute"/>';
			con += '<map code="0xf3" name="Ucircumflex"/>';
			con += '<map code="0xf4" name="Ugrave"/>';
			con += '<map code="0xf5" name="dotlessi"/>';
			con += '<map code="0xf6" name="circumflex"/>';
			con += '<map code="0xf7" name="tilde"/>';
			con += '<map code="0xf8" name="macron"/>';
			con += '<map code="0xf9" name="breve"/>';
			con += '<map code="0xfa" name="dotaccent"/>';
			con += '<map code="0xfb" name="ring"/>';
			con += '<map code="0xfc" name="cedilla"/>';
			con += '<map code="0xfd" name="hungarumlaut"/>';
			con += '<map code="0xfe" name="ogonek"/>';
			con += '<map code="0xff" name="caron"/>';
			*/
		con += '</cmap_format_6>';
		con += '<cmap_format_4 platformID="3" platEncID="1" language="0">';
			con += '<map code="0x20" name="space"/>';
			con += '<map code="0x21" name="exclam"/>';
			con += '<map code="0x22" name="quotedbl"/>';
			con += '<map code="0x23" name="numbersign"/>';
			con += '<map code="0x24" name="dollar"/>';
			con += '<map code="0x25" name="percent"/>';
			con += '<map code="0x26" name="ampersand"/>';
			con += '<map code="0x27" name="quotesingle"/>';
			con += '<map code="0x28" name="parenleft"/>';
			con += '<map code="0x29" name="parenright"/>';
			con += '<map code="0x2a" name="asterisk"/>';
			con += '<map code="0x2b" name="plus"/>';
			con += '<map code="0x2c" name="comma"/>';
			con += '<map code="0x2d" name="hyphen"/>';
			con += '<map code="0x2e" name="period"/>';
			con += '<map code="0x2f" name="slash"/>';
			con += '<map code="0x30" name="zero"/>';
			con += '<map code="0x31" name="one"/>';
			con += '<map code="0x32" name="two"/>';
			con += '<map code="0x33" name="three"/>';
			con += '<map code="0x34" name="four"/>';
			con += '<map code="0x35" name="five"/>';
			con += '<map code="0x36" name="six"/>';
			con += '<map code="0x37" name="seven"/>';
			con += '<map code="0x38" name="eight"/>';
			con += '<map code="0x39" name="nine"/>';
			con += '<map code="0x3a" name="colon"/>';
			con += '<map code="0x3b" name="semicolon"/>';
			con += '<map code="0x3c" name="less"/>';
			con += '<map code="0x3d" name="equal"/>';
			con += '<map code="0x3e" name="greater"/>';
			con += '<map code="0x3f" name="question"/>';
			con += '<map code="0x40" name="at"/>';
			con += '<map code="0x41" name="A"/>';
			con += '<map code="0x42" name="B"/>';
			con += '<map code="0x43" name="C"/>';
			con += '<map code="0x44" name="D"/>';
			con += '<map code="0x45" name="E"/>';
			con += '<map code="0x46" name="F"/>';
			con += '<map code="0x47" name="G"/>';
			con += '<map code="0x48" name="H"/>';
			con += '<map code="0x49" name="I"/>';
			con += '<map code="0x4a" name="J"/>';
			con += '<map code="0x4b" name="K"/>';
			con += '<map code="0x4c" name="L"/>';
			con += '<map code="0x4d" name="M"/>';
			con += '<map code="0x4e" name="N"/>';
			con += '<map code="0x4f" name="O"/>';
			con += '<map code="0x50" name="P"/>';
			con += '<map code="0x51" name="Q"/>';
			con += '<map code="0x52" name="R"/>';
			con += '<map code="0x53" name="S"/>';
			con += '<map code="0x54" name="T"/>';
			con += '<map code="0x55" name="U"/>';
			con += '<map code="0x56" name="V"/>';
			con += '<map code="0x57" name="W"/>';
			con += '<map code="0x58" name="X"/>';
			con += '<map code="0x59" name="Y"/>';
			con += '<map code="0x5a" name="Z"/>';
			con += '<map code="0x5b" name="bracketleft"/>';
			con += '<map code="0x5c" name="backslash"/>';
			con += '<map code="0x5d" name="bracketright"/>';
			con += '<map code="0x5e" name="asciicircum"/>';
			con += '<map code="0x5f" name="underscore"/>';
			con += '<map code="0x60" name="grave"/>';
			con += '<map code="0x61" name="a"/>';
			con += '<map code="0x62" name="b"/>';
			con += '<map code="0x63" name="c"/>';
			con += '<map code="0x64" name="d"/>';
			con += '<map code="0x65" name="e"/>';
			con += '<map code="0x66" name="f"/>';
			con += '<map code="0x67" name="g"/>';
			con += '<map code="0x68" name="h"/>';
			con += '<map code="0x69" name="i"/>';
			con += '<map code="0x6a" name="j"/>';
			con += '<map code="0x6b" name="k"/>';
			con += '<map code="0x6c" name="l"/>';
			con += '<map code="0x6d" name="m"/>';
			con += '<map code="0x6e" name="n"/>';
			con += '<map code="0x6f" name="o"/>';
			con += '<map code="0x70" name="p"/>';
			con += '<map code="0x71" name="q"/>';
			con += '<map code="0x72" name="r"/>';
			con += '<map code="0x73" name="s"/>';
			con += '<map code="0x74" name="t"/>';
			con += '<map code="0x75" name="u"/>';
			con += '<map code="0x76" name="v"/>';
			con += '<map code="0x77" name="w"/>';
			con += '<map code="0x78" name="x"/>';
			con += '<map code="0x79" name="y"/>';
			con += '<map code="0x7a" name="z"/>';
			con += '<map code="0x7b" name="braceleft"/>';
			con += '<map code="0x7c" name="bar"/>';
			con += '<map code="0x7d" name="braceright"/>';
			con += '<map code="0x7e" name="asciitilde"/>';
			/*
			con += '<map code="0xa0" name="uni00A0"/>';
			con += '<map code="0xa1" name="exclamdown"/>';
			con += '<map code="0xa2" name="cent"/>';
			con += '<map code="0xa3" name="sterling"/>';
			con += '<map code="0xa4" name="currency"/>';
			con += '<map code="0xa5" name="yen"/>';
			con += '<map code="0xa6" name="brokenbar"/>';
			con += '<map code="0xa7" name="section"/>';
			con += '<map code="0xa8" name="dieresis"/>';
			con += '<map code="0xa9" name="copyright"/>';
			con += '<map code="0xaa" name="ordfeminine"/>';
			con += '<map code="0xab" name="guillemotleft"/>';
			con += '<map code="0xac" name="logicalnot"/>';
			con += '<map code="0xad" name="uni00AD"/>';
			con += '<map code="0xae" name="registered"/>';
			con += '<map code="0xaf" name="macron"/>';
			con += '<map code="0xb0" name="degree"/>';
			con += '<map code="0xb1" name="plusminus"/>';
			con += '<map code="0xb2" name="twosuperior"/>';
			con += '<map code="0xb3" name="threesuperior"/>';
			con += '<map code="0xb4" name="acute"/>';
			con += '<map code="0xb5" name="mu"/>';
			con += '<map code="0xb6" name="paragraph"/>';
			con += '<map code="0xb7" name="periodcentered"/>';
			con += '<map code="0xb8" name="cedilla"/>';
			con += '<map code="0xb9" name="onesuperior"/>';
			con += '<map code="0xba" name="ordmasculine"/>';
			con += '<map code="0xbb" name="guillemotright"/>';
			con += '<map code="0xbc" name="onequarter"/>';
			con += '<map code="0xbd" name="onehalf"/>';
			con += '<map code="0xbe" name="threequarters"/>';
			con += '<map code="0xbf" name="questiondown"/>';
			con += '<map code="0xc0" name="Agrave"/>';
			con += '<map code="0xc1" name="Aacute"/>';
			con += '<map code="0xc2" name="Acircumflex"/>';
			con += '<map code="0xc3" name="Atilde"/>';
			con += '<map code="0xc4" name="Adieresis"/>';
			con += '<map code="0xc5" name="Aring"/>';
			con += '<map code="0xc6" name="AE"/>';
			con += '<map code="0xc7" name="Ccedilla"/>';
			con += '<map code="0xc8" name="Egrave"/>';
			con += '<map code="0xc9" name="Eacute"/>';
			con += '<map code="0xca" name="Ecircumflex"/>';
			con += '<map code="0xcb" name="Edieresis"/>';
			con += '<map code="0xcc" name="Igrave"/>';
			con += '<map code="0xcd" name="Iacute"/>';
			con += '<map code="0xce" name="Icircumflex"/>';
			con += '<map code="0xcf" name="Idieresis"/>';
			con += '<map code="0xd0" name="Eth"/>';
			con += '<map code="0xd1" name="Ntilde"/>';
			con += '<map code="0xd2" name="Ograve"/>';
			con += '<map code="0xd3" name="Oacute"/>';
			con += '<map code="0xd4" name="Ocircumflex"/>';
			con += '<map code="0xd5" name="Otilde"/>';
			con += '<map code="0xd6" name="Odieresis"/>';
			con += '<map code="0xd7" name="multiply"/>';
			con += '<map code="0xd8" name="Oslash"/>';
			con += '<map code="0xd9" name="Ugrave"/>';
			con += '<map code="0xda" name="Uacute"/>';
			con += '<map code="0xdb" name="Ucircumflex"/>';
			con += '<map code="0xdc" name="Udieresis"/>';
			con += '<map code="0xdd" name="Yacute"/>';
			con += '<map code="0xde" name="Thorn"/>';
			con += '<map code="0xdf" name="germandbls"/>';
			con += '<map code="0xe0" name="agrave"/>';
			con += '<map code="0xe1" name="aacute"/>';
			con += '<map code="0xe2" name="acircumflex"/>';
			con += '<map code="0xe3" name="atilde"/>';
			con += '<map code="0xe4" name="adieresis"/>';
			con += '<map code="0xe5" name="aring"/>';
			con += '<map code="0xe6" name="ae"/>';
			con += '<map code="0xe7" name="ccedilla"/>';
			con += '<map code="0xe8" name="egrave"/>';
			con += '<map code="0xe9" name="eacute"/>';
			con += '<map code="0xea" name="ecircumflex"/>';
			con += '<map code="0xeb" name="edieresis"/>';
			con += '<map code="0xec" name="igrave"/>';
			con += '<map code="0xed" name="iacute"/>';
			con += '<map code="0xee" name="icircumflex"/>';
			con += '<map code="0xef" name="idieresis"/>';
			con += '<map code="0xf0" name="eth"/>';
			con += '<map code="0xf1" name="ntilde"/>';
			con += '<map code="0xf2" name="ograve"/>';
			con += '<map code="0xf3" name="oacute"/>';
			con += '<map code="0xf4" name="ocircumflex"/>';
			con += '<map code="0xf5" name="otilde"/>';
			con += '<map code="0xf6" name="odieresis"/>';
			con += '<map code="0xf7" name="divide"/>';
			con += '<map code="0xf8" name="oslash"/>';
			con += '<map code="0xf9" name="ugrave"/>';
			con += '<map code="0xfa" name="uacute"/>';
			con += '<map code="0xfb" name="ucircumflex"/>';
			con += '<map code="0xfc" name="udieresis"/>';
			con += '<map code="0xfd" name="yacute"/>';
			con += '<map code="0xfe" name="thorn"/>';
			con += '<map code="0xff" name="ydieresis"/>';
			con += '<map code="0x131" name="dotlessi"/>';
			con += '<map code="0x141" name="Lslash"/>';
			con += '<map code="0x142" name="lslash"/>';
			con += '<map code="0x152" name="OE"/>';
			con += '<map code="0x153" name="oe"/>';
			con += '<map code="0x160" name="Scaron"/>';
			con += '<map code="0x161" name="scaron"/>';
			con += '<map code="0x178" name="Ydieresis"/>';
			con += '<map code="0x17d" name="Zcaron"/>';
			con += '<map code="0x17e" name="zcaron"/>';
			con += '<map code="0x192" name="florin"/>';
			con += '<map code="0x2c6" name="circumflex"/>';
			con += '<map code="0x2c7" name="caron"/>';
			con += '<map code="0x2c9" name="uni02C9"/>';
			con += '<map code="0x2d8" name="breve"/>';
			con += '<map code="0x2d9" name="dotaccent"/>';
			con += '<map code="0x2da" name="ring"/>';
			con += '<map code="0x2db" name="ogonek"/>';
			con += '<map code="0x2dc" name="tilde"/>';
			con += '<map code="0x2dd" name="hungarumlaut"/>';
			con += '<map code="0x3a9" name="uni03A9"/>';
			con += '<map code="0x3bc" name="uni03BC"/>';
			con += '<map code="0x3c0" name="pi"/>';
			con += '<map code="0x2010" name="uni2010"/>';
			con += '<map code="0x2013" name="endash"/>';
			con += '<map code="0x2014" name="emdash"/>';
			con += '<map code="0x2018" name="quoteleft"/>';
			con += '<map code="0x2019" name="quoteright"/>';
			con += '<map code="0x201a" name="quotesinglbase"/>';
			con += '<map code="0x201c" name="quotedblleft"/>';
			con += '<map code="0x201d" name="quotedblright"/>';
			con += '<map code="0x201e" name="quotedblbase"/>';
			con += '<map code="0x2020" name="dagger"/>';
			con += '<map code="0x2021" name="daggerdbl"/>';
			con += '<map code="0x2022" name="bullet"/>';
			con += '<map code="0x2026" name="ellipsis"/>';
			con += '<map code="0x2030" name="perthousand"/>';
			con += '<map code="0x2039" name="guilsinglleft"/>';
			con += '<map code="0x203a" name="guilsinglright"/>';
			con += '<map code="0x2044" name="fraction"/>';
			con += '<map code="0x20ac" name="Euro"/>';
			con += '<map code="0x2113" name="afii61289"/>';
			con += '<map code="0x2122" name="trademark"/>';
			con += '<map code="0x2126" name="Omega"/>';
			con += '<map code="0x212e" name="estimated"/>';
			con += '<map code="0x2202" name="partialdiff"/>';
			con += '<map code="0x2206" name="uni2206"/>';
			con += '<map code="0x220f" name="product"/>';
			con += '<map code="0x2211" name="summation"/>';
			con += '<map code="0x2212" name="minus"/>';
			con += '<map code="0x2215" name="uni2215"/>';
			con += '<map code="0x2219" name="uni2219"/>';
			con += '<map code="0x221a" name="radical"/>';
			con += '<map code="0x221e" name="infinity"/>';
			con += '<map code="0x222b" name="integral"/>';
			con += '<map code="0x2248" name="approxequal"/>';
			con += '<map code="0x2260" name="notequal"/>';
			con += '<map code="0x2264" name="lessequal"/>';
			con += '<map code="0x2265" name="greaterequal"/>';
			con += '<map code="0x25ca" name="lozenge"/>';
			con += '<map code="0xfb01" name="fi"/>';
			con += '<map code="0xfb02" name="fl"/>';
			*/
		con += '</cmap_format_4>';

		
		con += '</cmap>';
		return con;
	}

	function genTable_post(oa){
		var con = '<post>';
		con += '<formatType value="3.0"/>';
		con += '<italicAngle value="0.0"/>';
		con += '<underlinePosition value="-75"/>';
		con += '<underlineThickness value="50"/>';
		con += '<isFixedPitch value="0"/>';
		con += '<minMemType42 value="0"/>';
		con += '<maxMemType42 value="0"/>';
		con += '<minMemType1 value="0"/>';
		con += '<maxMemType1 value="0"/>';		
		
		con += '</post>';
		return con;
	}

	function genTable_cff(oa){
		var con = '<CFF>';
		con += '<CFFFont name="HoboStd">';
		con += '<version value="002.000"/>';
		con += '<Notice value="Copyright 1987, 1990, 1994, 2001, 2002 Adobe Systems Incorporated. All rights reserved. Hobo"/>';
		con += '<FullName value="Hobo Std Medium"/>';
		con += '<FamilyName value="Hobo Std"/>';
		con += '<Weight value="Medium"/>';
		con += '<isFixedPitch value="0"/>';
		con += '<ItalicAngle value="0"/>';
		con += '<UnderlineThickness value="50"/>';
		con += '<PaintType value="0"/>';
		con += '<CharstringType value="2"/>';
		con += '<FontMatrix value="0.001 0 0 0.001 0 0"/>';
		con += '<FontBBox value="-123 -315 1264 1101"/>';
		con += '<StrokeWidth value="0"/>';
		con += '<Encoding name="StandardEncoding"/>';
		con += '<Private>';
			con += '<BlueValues value="-15 0 832 847 640 655"/>';
			con += '<OtherBlues value="-206 -200"/>';
			con += '<BlueScale value="0.039625"/>';
			con += '<BlueShift value="7"/>';
			con += '<BlueFuzz value="1"/>';
			con += '<StdHW value="118"/>';
			con += '<StdVW value="135"/>';
			con += '<ForceBold value="0"/>';
			con += '<LanguageGroup value="0"/>';
			con += '<ExpansionFactor value="0.06"/>';
			con += '<initialRandomSeed value="0"/>';
			con += '<defaultWidthX value="580"/>';
			con += '<nominalWidthX value="607"/>';
		con += '</Private>';
		con += '<CharStrings>';

		con += genCharStringsPostScript();

		con += '</CharStrings>';
		con += '</CFFFont>';
		con += '</CFF>';
		return con;
	}

	function genTable_hmtx(oa){
		var con = '<hmtx>';
		con += '<mtx name=".notdef" width="500" lsb="0"/>';
		con += '<mtx name="A" width="698" lsb="33"/>';
		con += '<mtx name="AE" width="1055" lsb="33"/>';
		con += '<mtx name="Aacute" width="698" lsb="33"/>';
		con += '<mtx name="Acircumflex" width="698" lsb="33"/>';
		con += '<mtx name="Adieresis" width="698" lsb="33"/>';
		con += '<mtx name="Agrave" width="698" lsb="33"/>';
		con += '<mtx name="Aring" width="698" lsb="33"/>';
		con += '<mtx name="Atilde" width="698" lsb="33"/>';
		con += '<mtx name="B" width="662" lsb="50"/>';
		con += '<mtx name="C" width="645" lsb="25"/>';
		con += '<mtx name="Ccedilla" width="645" lsb="25"/>';
		con += '<mtx name="D" width="670" lsb="50"/>';
		con += '<mtx name="E" width="597" lsb="50"/>';
		con += '<mtx name="Eacute" width="597" lsb="50"/>';
		con += '<mtx name="Ecircumflex" width="597" lsb="50"/>';
		con += '<mtx name="Edieresis" width="597" lsb="50"/>';
		con += '<mtx name="Egrave" width="597" lsb="50"/>';
		con += '<mtx name="Eth" width="670" lsb="-12"/>';
		con += '<mtx name="Euro" width="580" lsb="19"/>';
		con += '<mtx name="F" width="548" lsb="50"/>';
		con += '<mtx name="G" width="659" lsb="25"/>';
		con += '<mtx name="H" width="711" lsb="50"/>';
		con += '<mtx name="I" width="327" lsb="62"/>';
		con += '<mtx name="Iacute" width="327" lsb="62"/>';
		con += '<mtx name="Icircumflex" width="327" lsb="-9"/>';
		con += '<mtx name="Idieresis" width="327" lsb="-40"/>';
		con += '<mtx name="Igrave" width="327" lsb="21"/>';
		con += '<mtx name="J" width="400" lsb="0"/>';
		con += '<mtx name="K" width="652" lsb="50"/>';
		con += '<mtx name="L" width="551" lsb="50"/>';
		con += '<mtx name="Lslash" width="551" lsb="-43"/>';
		con += '<mtx name="M" width="867" lsb="50"/>';
		con += '<mtx name="N" width="709" lsb="50"/>';
		con += '<mtx name="Ntilde" width="709" lsb="50"/>';
		con += '<mtx name="O" width="712" lsb="25"/>';
		con += '<mtx name="OE" width="1077" lsb="25"/>';
		con += '<mtx name="Oacute" width="712" lsb="25"/>';
		con += '<mtx name="Ocircumflex" width="712" lsb="25"/>';
		con += '<mtx name="Odieresis" width="712" lsb="25"/>';
		con += '<mtx name="Ograve" width="712" lsb="25"/>';
		con += '<mtx name="Omega" width="722" lsb="33"/>';
		con += '<mtx name="Oslash" width="712" lsb="-16"/>';
		con += '<mtx name="Otilde" width="712" lsb="25"/>';
		con += '<mtx name="P" width="624" lsb="50"/>';
		con += '<mtx name="Q" width="723" lsb="50"/>';
		con += '<mtx name="R" width="664" lsb="50"/>';
		con += '<mtx name="S" width="646" lsb="33"/>';
		con += '<mtx name="Scaron" width="646" lsb="33"/>';
		con += '<mtx name="T" width="1000" lsb="0"/>';
		con += '<mtx name="Thorn" width="624" lsb="77"/>';
		con += '<mtx name="U" width="673" lsb="33"/>';
		con += '<mtx name="Uacute" width="673" lsb="33"/>';
		con += '<mtx name="Ucircumflex" width="673" lsb="33"/>';
		con += '<mtx name="Udieresis" width="673" lsb="33"/>';
		con += '<mtx name="Ugrave" width="673" lsb="33"/>';
		con += '<mtx name="V" width="644" lsb="17"/>';
		con += '<mtx name="W" width="851" lsb="16"/>';
		con += '<mtx name="X" width="636" lsb="25"/>';
		con += '<mtx name="Y" width="644" lsb="16"/>';
		con += '<mtx name="Yacute" width="644" lsb="16"/>';
		con += '<mtx name="Ydieresis" width="644" lsb="16"/>';
		con += '<mtx name="Z" width="620" lsb="16"/>';
		con += '<mtx name="Zcaron" width="620" lsb="16"/>';
		con += '<mtx name="a" width="520" lsb="33"/>';
		con += '<mtx name="a.superior" width="400" lsb="25"/>';
		con += '<mtx name="aacute" width="520" lsb="33"/>';
		con += '<mtx name="acircumflex" width="520" lsb="33"/>';
		con += '<mtx name="acute" width="385" lsb="117"/>';
		con += '<mtx name="adieresis" width="520" lsb="33"/>';
		con += '<mtx name="ae" width="821" lsb="33"/>';
		con += '<mtx name="afii61289" width="546" lsb="21"/>';
		con += '<mtx name="agrave" width="520" lsb="33"/>';
		con += '<mtx name="ampersand" width="958" lsb="50"/>';
		con += '<mtx name="approxequal" width="580" lsb="39"/>';
		con += '<mtx name="aring" width="520" lsb="33"/>';
		con += '<mtx name="asciicircum" width="586" lsb="43"/>';
		con += '<mtx name="asciitilde" width="580" lsb="38"/>';
		con += '<mtx name="asterisk" width="647" lsb="128"/>';
		con += '<mtx name="at" width="873" lsb="46"/>';
		con += '<mtx name="atilde" width="520" lsb="33"/>';
		con += '<mtx name="b" width="536" lsb="46"/>';
		con += '<mtx name="backslash" width="362" lsb="10"/>';
		con += '<mtx name="bar" width="341" lsb="103"/>';
		con += '<mtx name="braceleft" width="400" lsb="15"/>';
		con += '<mtx name="braceright" width="400" lsb="25"/>';
		con += '<mtx name="bracketleft" width="400" lsb="75"/>';
		con += '<mtx name="bracketright" width="400" lsb="50"/>';
		con += '<mtx name="breve" width="400" lsb="30"/>';
		con += '<mtx name="brokenbar" width="341" lsb="103"/>';
		con += '<mtx name="bullet" width="400" lsb="0"/>';
		con += '<mtx name="c" width="488" lsb="21"/>';
		con += '<mtx name="caron" width="550" lsb="83"/>';
		con += '<mtx name="ccedilla" width="488" lsb="21"/>';
		con += '<mtx name="cedilla" width="500" lsb="113"/>';
		con += '<mtx name="cent" width="580" lsb="73"/>';
		con += '<mtx name="circumflex" width="550" lsb="83"/>';
		con += '<mtx name="colon" width="290" lsb="33"/>';
		con += '<mtx name="comma" width="290" lsb="25"/>';
		con += '<mtx name="copyright" width="928" lsb="33"/>';
		con += '<mtx name="currency" width="597" lsb="60"/>';
		con += '<mtx name="d" width="542" lsb="21"/>';
		con += '<mtx name="dagger" width="582" lsb="41"/>';
		con += '<mtx name="daggerdbl" width="582" lsb="41"/>';
		con += '<mtx name="degree" width="414" lsb="41"/>';
		con += '<mtx name="dieresis" width="567" lsb="80"/>';
		con += '<mtx name="divide" width="580" lsb="51"/>';
		con += '<mtx name="dollar" width="580" lsb="21"/>';
		con += '<mtx name="dotaccent" width="500" lsb="161"/>';
		con += '<mtx name="dotlessi" width="266" lsb="46"/>';
		con += '<mtx name="e" width="525" lsb="21"/>';
		con += '<mtx name="eacute" width="525" lsb="21"/>';
		con += '<mtx name="ecircumflex" width="525" lsb="21"/>';
		con += '<mtx name="edieresis" width="525" lsb="21"/>';
		con += '<mtx name="egrave" width="525" lsb="21"/>';
		con += '<mtx name="eight" width="580" lsb="25"/>';
		con += '<mtx name="ellipsis" width="1000" lsb="55"/>';
		con += '<mtx name="emdash" width="1000" lsb="-25"/>';
		con += '<mtx name="endash" width="500" lsb="-25"/>';
		con += '<mtx name="equal" width="580" lsb="51"/>';
		con += '<mtx name="estimated" width="1014" lsb="39"/>';
		con += '<mtx name="eth" width="544" lsb="21"/>';
		con += '<mtx name="exclam" width="325" lsb="50"/>';
		con += '<mtx name="exclamdown" width="325" lsb="50"/>';
		con += '<mtx name="f" width="358" lsb="8"/>';
		con += '<mtx name="f_i" width="604" lsb="8"/>';
		con += '<mtx name="f_l" width="594" lsb="8"/>';
		con += '<mtx name="fi" width="604" lsb="8"/>';
		con += '<mtx name="five" width="580" lsb="47"/>';
		con += '<mtx name="fl" width="594" lsb="8"/>';
		con += '<mtx name="florin" width="580" lsb="45"/>';
		con += '<mtx name="four" width="580" lsb="21"/>';
		con += '<mtx name="fraction" width="231" lsb="-123"/>';
		con += '<mtx name="g" width="556" lsb="25"/>';
		con += '<mtx name="germandbls" width="557" lsb="50"/>';
		con += '<mtx name="grave" width="385" lsb="50"/>';
		con += '<mtx name="greater" width="580" lsb="53"/>';
		con += '<mtx name="greaterequal" width="580" lsb="54"/>';
		con += '<mtx name="guillemotleft" width="608" lsb="50"/>';
		con += '<mtx name="guillemotright" width="608" lsb="50"/>';
		con += '<mtx name="guilsinglleft" width="358" lsb="50"/>';
		con += '<mtx name="guilsinglright" width="358" lsb="50"/>';
		con += '<mtx name="h" width="544" lsb="50"/>';
		con += '<mtx name="hungarumlaut" width="567" lsb="62"/>';
		con += '<mtx name="hyphen" width="250" lsb="0"/>';
		con += '<mtx name="i" width="266" lsb="46"/>';
		con += '<mtx name="iacute" width="266" lsb="46"/>';
		con += '<mtx name="icircumflex" width="266" lsb="-59"/>';
		con += '<mtx name="idieresis" width="266" lsb="-70"/>';
		con += '<mtx name="igrave" width="266" lsb="-9"/>';
		con += '<mtx name="infinity" width="858" lsb="52"/>';
		con += '<mtx name="integral" width="453" lsb="31"/>';
		con += '<mtx name="j" width="302" lsb="0"/>';
		con += '<mtx name="k" width="514" lsb="46"/>';
		con += '<mtx name="l" width="257" lsb="54"/>';
		con += '<mtx name="less" width="580" lsb="53"/>';
		con += '<mtx name="lessequal" width="580" lsb="53"/>';
		con += '<mtx name="logicalnot" width="580" lsb="51"/>';
		con += '<mtx name="lozenge" width="638" lsb="53"/>';
		con += '<mtx name="lslash" width="257" lsb="-30"/>';
		con += '<mtx name="m" width="845" lsb="45"/>';
		con += '<mtx name="macron" width="500" lsb="115"/>';
		con += '<mtx name="minus" width="580" lsb="51"/>';
		con += '<mtx name="mu" width="556" lsb="46"/>';
		con += '<mtx name="multiply" width="580" lsb="37"/>';
		con += '<mtx name="n" width="552" lsb="46"/>';
		con += '<mtx name="nine" width="580" lsb="33"/>';
		con += '<mtx name="notequal" width="580" lsb="51"/>';
		con += '<mtx name="ntilde" width="552" lsb="46"/>';
		con += '<mtx name="numbersign" width="618" lsb="31"/>';
		con += '<mtx name="o" width="544" lsb="21"/>';
		con += '<mtx name="o.superior" width="400" lsb="10"/>';
		con += '<mtx name="oacute" width="544" lsb="21"/>';
		con += '<mtx name="ocircumflex" width="544" lsb="21"/>';
		con += '<mtx name="odieresis" width="544" lsb="21"/>';
		con += '<mtx name="oe" width="892" lsb="21"/>';
		con += '<mtx name="ogonek" width="400" lsb="44"/>';
		con += '<mtx name="ograve" width="544" lsb="21"/>';
		con += '<mtx name="one" width="580" lsb="140"/>';
		con += '<mtx name="one.superior" width="350" lsb="64"/>';
		con += '<mtx name="onehalf" width="906" lsb="28"/>';
		con += '<mtx name="onequarter" width="867" lsb="28"/>';
		con += '<mtx name="onesuperior" width="350" lsb="64"/>';
		con += '<mtx name="ordfeminine" width="400" lsb="25"/>';
		con += '<mtx name="ordmasculine" width="400" lsb="10"/>';
		con += '<mtx name="oslash" width="544" lsb="2"/>';
		con += '<mtx name="otilde" width="544" lsb="21"/>';
		con += '<mtx name="p" width="525" lsb="46"/>';
		con += '<mtx name="paragraph" width="583" lsb="39"/>';
		con += '<mtx name="parenleft" width="461" lsb="75"/>';
		con += '<mtx name="parenright" width="461" lsb="75"/>';
		con += '<mtx name="partialdiff" width="618" lsb="41"/>';
		con += '<mtx name="percent" width="794" lsb="46"/>';
		con += '<mtx name="period" width="290" lsb="33"/>';
		con += '<mtx name="periodcentered" width="290" lsb="33"/>';
		con += '<mtx name="perthousand" width="1293" lsb="28"/>';
		con += '<mtx name="pi" width="644" lsb="4"/>';
		con += '<mtx name="plus" width="580" lsb="50"/>';
		con += '<mtx name="plusminus" width="580" lsb="50"/>';
		con += '<mtx name="product" width="773" lsb="28"/>';
		con += '<mtx name="q" width="525" lsb="13"/>';
		con += '<mtx name="question" width="480" lsb="50"/>';
		con += '<mtx name="questiondown" width="480" lsb="50"/>';
		con += '<mtx name="quotedbl" width="333" lsb="25"/>';
		con += '<mtx name="quotedblbase" width="615" lsb="50"/>';
		con += '<mtx name="quotedblleft" width="615" lsb="50"/>';
		con += '<mtx name="quotedblright" width="615" lsb="50"/>';
		con += '<mtx name="quoteleft" width="340" lsb="50"/>';
		con += '<mtx name="quoteright" width="340" lsb="50"/>';
		con += '<mtx name="quotesinglbase" width="340" lsb="50"/>';
		con += '<mtx name="quotesingle" width="222" lsb="62"/>';
		con += '<mtx name="r" width="426" lsb="46"/>';
		con += '<mtx name="radical" width="639" lsb="35"/>';
		con += '<mtx name="registered" width="928" lsb="33"/>';
		con += '<mtx name="ring" width="400" lsb="77"/>';
		con += '<mtx name="s" width="517" lsb="39"/>';
		con += '<mtx name="scaron" width="517" lsb="39"/>';
		con += '<mtx name="section" width="608" lsb="54"/>';
		con += '<mtx name="semicolon" width="290" lsb="25"/>';
		con += '<mtx name="seven" width="580" lsb="60"/>';
		con += '<mtx name="six" width="580" lsb="33"/>';
		con += '<mtx name="slash" width="527" lsb="46"/>';
		con += '<mtx name="space" width="290" lsb="0"/>';
		con += '<mtx name="sterling" width="580" lsb="-6"/>';
		con += '<mtx name="summation" width="587" lsb="27"/>';
		con += '<mtx name="t" width="363" lsb="13"/>';
		con += '<mtx name="thorn" width="525" lsb="46"/>';
		con += '<mtx name="three" width="580" lsb="46"/>';
		con += '<mtx name="three.superior" width="350" lsb="17"/>';
		con += '<mtx name="threequarters" width="927" lsb="29"/>';
		con += '<mtx name="threesuperior" width="350" lsb="17"/>';
		con += '<mtx name="tilde" width="410" lsb="0"/>';
		con += '<mtx name="trademark" width="1000" lsb="5"/>';
		con += '<mtx name="two" width="580" lsb="46"/>';
		con += '<mtx name="two.superior" width="350" lsb="16"/>';
		con += '<mtx name="twosuperior" width="350" lsb="16"/>';
		con += '<mtx name="u" width="556" lsb="46"/>';
		con += '<mtx name="uacute" width="556" lsb="46"/>';
		con += '<mtx name="ucircumflex" width="556" lsb="46"/>';
		con += '<mtx name="udieresis" width="556" lsb="46"/>';
		con += '<mtx name="ugrave" width="556" lsb="46"/>';
		con += '<mtx name="underscore" width="500" lsb="-25"/>';
		con += '<mtx name="uni00A0" width="290" lsb="0"/>';
		con += '<mtx name="uni00AD" width="250" lsb="0"/>';
		con += '<mtx name="uni02C9" width="500" lsb="115"/>';
		con += '<mtx name="uni03A9" width="722" lsb="33"/>';
		con += '<mtx name="uni03BC" width="556" lsb="46"/>';
		con += '<mtx name="uni2010" width="250" lsb="0"/>';
		con += '<mtx name="uni2206" width="690" lsb="28"/>';
		con += '<mtx name="uni2215" width="231" lsb="-123"/>';
		con += '<mtx name="uni2219" width="290" lsb="33"/>';
		con += '<mtx name="v" width="516" lsb="21"/>';
		con += '<mtx name="w" width="722" lsb="21"/>';
		con += '<mtx name="x" width="510" lsb="26"/>';
		con += '<mtx name="y" width="513" lsb="26"/>';
		con += '<mtx name="yacute" width="513" lsb="26"/>';
		con += '<mtx name="ydieresis" width="513" lsb="26"/>';
		con += '<mtx name="yen" width="580" lsb="1"/>';
		con += '<mtx name="z" width="467" lsb="26"/>';
		con += '<mtx name="zcaron" width="467" lsb="26"/>';
		con += '<mtx name="zero" width="580" lsb="33"/>';		
		
		con += '</hmtx>';
		return con;
	}
	