function decToHex(d) { return Number(d).toString(16); }
function hexToDec(h) { return parseInt(h,16); }

var unicodenames = {
// Basic Latin
	"0020": "Space",
	"0021": "Exclamation mark",
	"0022": "Quotation mark",
	"0023": "Number sign, Hash tag",
	"0024": "Dollar sign",
	"0025": "Percent sign",
	"0026": "Ampersand",
	"0027": "Apostrophe",
	"0028": "Left parenthesis",
	"0029": "Right parenthesis",
	"002A": "Asterisk",
	"002B": "Plus sign",
	"002C": "Comma",
	"002D": "Hyphen-minus",
	"002E": "Full stop",
	"002F": "Slash (Solidus)",
	"0030": "Digit Zero",
	"0031": "Digit One",
	"0032": "Digit Two",
	"0033": "Digit Three",
	"0034": "Digit Four",
	"0035": "Digit Five",
	"0036": "Digit Six",
	"0037": "Digit Seven",
	"0038": "Digit Eight",
	"0039": "Digit Nine",
	"003A": "Colon",
	"003B": "Semicolon",
	"003C": "Less-than sign",
	"003D": "Equal sign",
	"003E": "Greater-than sign",
	"003F": "Question mark",
	"0040": "At sign",
	"0041": "Latin Capital letter A",
	"0042": "Latin Capital letter B",
	"0043": "Latin Capital letter C",
	"0044": "Latin Capital letter D",
	"0045": "Latin Capital letter E",
	"0046": "Latin Capital letter F",
	"0047": "Latin Capital letter G",
	"0048": "Latin Capital letter H",
	"0049": "Latin Capital letter I",
	"004A": "Latin Capital letter J",
	"004B": "Latin Capital letter K",
	"004C": "Latin Capital letter L",
	"004D": "Latin Capital letter M",
	"004E": "Latin Capital letter N",
	"004F": "Latin Capital letter O",
	"0050": "Latin Capital letter P",
	"0051": "Latin Capital letter Q",
	"0052": "Latin Capital letter R",
	"0053": "Latin Capital letter S",
	"0054": "Latin Capital letter T",
	"0055": "Latin Capital letter U",
	"0056": "Latin Capital letter V",
	"0057": "Latin Capital letter W",
	"0058": "Latin Capital letter X",
	"0059": "Latin Capital letter Y",
	"005A": "Latin Capital letter Z",
	"005B": "Left Square Bracket",
	"005C": "Backslash",
	"005D": "Right Square Bracket",
	"005E": "Circumflex accent",
	"005F": "Low line",
	"0060": "Grave accent",
	"0061": "Latin Small Letter A",
	"0062": "Latin Small Letter B",
	"0063": "Latin Small Letter C",
	"0064": "Latin Small Letter D",
	"0065": "Latin Small Letter E",
	"0066": "Latin Small Letter F",
	"0067": "Latin Small Letter G",
	"0068": "Latin Small Letter H",
	"0069": "Latin Small Letter I",
	"006A": "Latin Small Letter J",
	"006B": "Latin Small Letter K",
	"006C": "Latin Small Letter L",
	"006D": "Latin Small Letter M",
	"006E": "Latin Small Letter N",
	"006F": "Latin Small Letter O",
	"0070": "Latin Small Letter P",
	"0071": "Latin Small Letter Q",
	"0072": "Latin Small Letter R",
	"0073": "Latin Small Letter S",
	"0074": "Latin Small Letter T",
	"0075": "Latin Small Letter U",
	"0076": "Latin Small Letter V",
	"0077": "Latin Small Letter W",
	"0078": "Latin Small Letter X",
	"0079": "Latin Small Letter Y",
	"007A": "Latin Small Letter Z",
	"007B": "Left Curly Bracket",
	"007C": "Vertical bar",
	"007D": "Right Curly Bracket",
	"007E": "Tilde",

// Latin-1 Suppliment
	"00A1": "Inverted Exclamation Mark",
	"00A2": "Cent sign",
	"00A3": "Pound sign",
	"00A4": "Currency sign",
	"00A5": "Yen sign",
	"00A6": "Broken bar",
	"00A7": "Section sign",
	"00A8": "Diaeresis",
	"00A9": "Copyright sign",
	"00AA": "Feminine Ordinal Indicator",
	"00AB": "Left-pointing double angle quotation mark",
	"00AC": "Not sign",
	"00AD": "Soft hyphen",
	"00AE": "Registered sign",
	"00AF": "Macron",
	"00B0": "Degree symbol",
	"00B1": "Plus-minus sign",
	"00B2": "Superscript two",
	"00B3": "Superscript three",
	"00B4": "Acute accent",
	"00B5": "Micro sign",
	"00B6": "Pilcrow sign",
	"00B7": "Middle dot",
	"00B8": "Cedilla",
	"00B9": "Superscript one",
	"00BA": "Masculine ordinal indicator",
	"00BB": "Right-pointing double angle quotation mark",
	"00BC": "Vulgar fraction one quarter",
	"00BD": "Vulgar fraction one half",
	"00BE": "Vulgar fraction three quarters",
	"00BF": "Inverted Question Mark",
	"00C0": "Latin Capital Letter A with grave",
	"00C1": "Latin Capital letter A with acute",
	"00C2": "Latin Capital letter A with circumflex",
	"00C3": "Latin Capital letter A with tilde",
	"00C4": "Latin Capital letter A with diaeresis",
	"00C5": "Latin Capital letter A with ring above",
	"00C6": "Latin Capital letter Æ",
	"00C7": "Latin Capital letter C with cedilla",
	"00C8": "Latin Capital letter E with grave",
	"00C9": "Latin Capital letter E with acute",
	"00CA": "Latin Capital letter E with circumflex",
	"00CB": "Latin Capital letter E with diaeresis",
	"00CC": "Latin Capital letter I with grave",
	"00CD": "Latin Capital letter I with acute",
	"00CE": "Latin Capital letter I with circumflex",
	"00CF": "Latin Capital letter I with diaeresis",
	"00D0": "Latin Capital letter Eth",
	"00D1": "Latin Capital letter N with tilde",
	"00D2": "Latin Capital letter O with grave",
	"00D3": "Latin Capital letter O with acute",
	"00D4": "Latin Capital letter O with circumflex",
	"00D5": "Latin Capital letter O with tilde",
	"00D6": "Latin Capital letter O with diaeresis",
	"00D7": "Multiplication sign",
	"00D8": "Latin Capital letter O with stroke",
	"00D9": "Latin Capital letter U with grave",
	"00DA": "Latin Capital letter U with acute",
	"00DB": "Latin Capital Letter U with circumflex",
	"00DC": "Latin Capital Letter U with diaeresis",
	"00DD": "Latin Capital Letter Y with acute",
	"00DE": "Latin Capital Letter Thorn",
	"00DF": "Latin Small Letter sharp S",
	"00E0": "Latin Small Letter A with grave",
	"00E1": "Latin Small Letter A with acute",
	"00E2": "Latin Small Letter A with circumflex",
	"00E3": "Latin Small Letter A with tilde",
	"00E4": "Latin Small Letter A with diaeresis",
	"00E5": "Latin Small Letter A with ring above",
	"00E6": "Latin Small Letter Æ",
	"00E7": "Latin Small Letter C with cedilla",
	"00E8": "Latin Small Letter E with grave",
	"00E9": "Latin Small Letter E with acute",
	"00EA": "Latin Small Letter E with circumflex",
	"00EB": "Latin Small Letter E with diaeresis",
	"00EC": "Latin Small Letter I with grave",
	"00ED": "Latin Small Letter I with acute",
	"00EE": "Latin Small Letter I with circumflex",
	"00EF": "Latin Small Letter I with diaeresis",
	"00F0": "Latin Small Letter Eth",
	"00F1": "Latin Small Letter N with tilde",
	"00F2": "Latin Small Letter O with grave",
	"00F3": "Latin Small Letter O with acute",
	"00F4": "Latin Small Letter O with circumflex",
	"00F5": "Latin Small Letter O with tilde",
	"00F6": "Latin Small Letter O with diaeresis",
	"00F7": "Division sign",
	"00F8": "Latin Small Letter O with stroke",
	"00F9": "Latin Small Letter U with grave",
	"00FA": "Latin Small Letter U with acute",
	"00FB": "Latin Small Letter U with circumflex",
	"00FC": "Latin Small Letter U with diaeresis",
	"00FD": "Latin Small Letter Y with acute",
	"00FE": "Latin Small Letter Thorn",
	"00FF": "Latin Small Letter Y with diaeresis",

// Latin Extended-A
	"0100": "Latin Capital Letter A with macron",
	"0101": "Latin Small Letter A with macron",
	"0102": "Latin Capital Letter A with breve",
	"0103": "Latin Small Letter A with breve",
	"0104": "Latin Capital Letter A with ogonek",
	"0105": "Latin Small Letter A with ogonek",
	"0106": "Latin Capital Letter C with acute",
	"0107": "Latin Small Letter C with acute",
	"0108": "Latin Capital Letter C with circumflex",
	"0109": "Latin Small Letter C with circumflex",
	"010A": "Latin Capital Letter C with dot above",
	"010B": "Latin Small Letter C with dot above",
	"010C": "Latin Capital Letter C with caron",
	"010D": "Latin Small Letter C with caron",
	"010E": "Latin Capital Letter D with caron",
	"010F": "Latin Small Letter D with caron",
	"0110": "Latin Capital Letter D with stroke",
	"0111": "Latin Small Letter D with stroke",
	"0112": "Latin Capital Letter E with macron",
	"0113": "Latin Small Letter E with macron",
	"0114": "Latin Capital Letter E with breve",
	"0115": "Latin Small Letter E with breve",
	"0116": "Latin Capital Letter E with dot above",
	"0117": "Latin Small Letter E with dot above",
	"0118": "Latin Capital Letter E with ogonek",
	"0119": "Latin Small Letter E with ogonek",
	"011A": "Latin Capital Letter E with caron",
	"011B": "Latin Small Letter E with caron",
	"011C": "Latin Capital Letter G with circumflex",
	"011D": "Latin Small Letter G with circumflex",
	"011E": "Latin Capital Letter G with breve",
	"011F": "Latin Small Letter G with breve",
	"0120": "Latin Capital Letter G with dot above",
	"0121": "Latin Small Letter G with dot above",
	"0122": "Latin Capital Letter G with cedilla",
	"0123": "Latin Small Letter G with cedilla",
	"0124": "Latin Capital Letter H with circumflex",
	"0125": "Latin Small Letter H with circumflex",
	"0126": "Latin Capital Letter H with stroke",
	"0127": "Latin Small Letter H with stroke",
	"0128": "Latin Capital Letter I with tilde",
	"0129": "Latin Small Letter I with tilde",
	"012A": "Latin Capital Letter I with macron",
	"012B": "Latin Small Letter I with macron",
	"012C": "Latin Capital Letter I with breve",
	"012D": "Latin Small Letter I with breve",
	"012E": "Latin Capital Letter I with ogonek",
	"012F": "Latin Small Letter I with ogonek",
	"0130": "Latin Capital Letter I with dot above",
	"0131": "Latin Small Letter dotless I",
	"0132": "Latin Capital Ligature IJ",
	"0133": "Latin Small Ligature IJ",
	"0134": "Latin Capital Letter J with circumflex",
	"0135": "Latin Small Letter J with circumflex",
	"0136": "Latin Capital Letter K with cedilla",
	"0137": "Latin Small Letter K with cedilla",
	"0138": "Latin Small Letter Kra",
	"0139": "Latin Capital Letter L with acute",
	"013A": "Latin Small Letter L with acute",
	"013B": "Latin Capital Letter L with cedilla",
	"013C": "Latin Small Letter L with cedilla",
	"013D": "Latin Capital Letter L with caron",
	"013E": "Latin Small Letter L with caron",
	"013F": "Latin Capital Letter L with middle dot",
	"0140": "Latin Small Letter L with middle dot",
	"0141": "Latin Capital Letter L with stroke",
	"0142": "Latin Small Letter L with stroke",
	"0143": "Latin Capital Letter N with acute",
	"0144": "Latin Small Letter N with acute",
	"0145": "Latin Capital Letter N with cedilla",
	"0146": "Latin Small Letter N with cedilla",
	"0147": "Latin Capital Letter N with caron",
	"0148": "Latin Small Letter N with caron",
	"0149": "Latin Small Letter N preceded by apostrophe[1]",
	"014A": "Latin Capital Letter Eng",
	"014B": "Latin Small Letter Eng",
	"014C": "Latin Capital Letter O with macron",
	"014D": "Latin Small Letter O with macron",
	"014E": "Latin Capital Letter O with breve",
	"014F": "Latin Small Letter O with breve",
	"0150": "Latin Capital Letter O with double acute",
	"0151": "Latin Small Letter O with double acute",
	"0152": "Latin Capital Ligature OE",
	"0153": "Latin Small Ligature OE",
	"0154": "Latin Capital Letter R with acute",
	"0155": "Latin Small Letter R with acute",
	"0156": "Latin Capital Letter R with cedilla",
	"0157": "Latin Small Letter R with cedilla",
	"0158": "Latin Capital Letter R with caron",
	"0159": "Latin Small Letter R with caron",
	"015A": "Latin Capital Letter S with acute",
	"015B": "Latin Small Letter S with acute",
	"015C": "Latin Capital Letter S with circumflex",
	"015D": "Latin Small Letter S with circumflex",
	"015E": "Latin Capital Letter S with cedilla",
	"015F": "Latin Small Letter S with cedilla",
	"0160": "Latin Capital Letter S with caron",
	"0161": "Latin Small Letter S with caron",
	"0162": "Latin Capital Letter T with cedilla",
	"0163": "Latin Small Letter T with cedilla",
	"0164": "Latin Capital Letter T with caron",
	"0165": "Latin Small Letter T with caron",
	"0166": "Latin Capital Letter T with stroke",
	"0167": "Latin Small Letter T with stroke",
	"0168": "Latin Capital Letter U with tilde",
	"0169": "Latin Small Letter U with tilde",
	"016A": "Latin Capital Letter U with macron",
	"016B": "Latin Small Letter U with macron",
	"016C": "Latin Capital Letter U with breve",
	"016D": "Latin Small Letter U with breve",
	"016E": "Latin Capital Letter U with ring above",
	"016F": "Latin Small Letter U with ring above",
	"0170": "Latin Capital Letter U with double acute",
	"0171": "Latin Small Letter U with double acute",
	"0172": "Latin Capital Letter U with ogonek",
	"0173": "Latin Small Letter U with ogonek",
	"0174": "Latin Capital Letter W with circumflex",
	"0175": "Latin Small Letter W with circumflex",
	"0176": "Latin Capital Letter Y with circumflex",
	"0177": "Latin Small Letter Y with circumflex",
	"0178": "Latin Capital Letter Y with diaeresis",
	"0179": "Latin Capital Letter Z with acute",
	"017A": "Latin Small Letter Z with acute",
	"017B": "Latin Capital Letter Z with dot above",
	"017C": "Latin Small Letter Z with dot above",
	"017D": "Latin Capital Letter Z with caron",
	"017E": "Latin Small Letter Z with caron",
	"017F": "Latin Small Letter long S",

// Latin Extended-B
	"0180": "Latin Small Letter B with stroke",
	"0181": "Latin Capital Letter B with hook",
	"0182": "Latin Capital Letter B with top bar",
	"0183": "Latin Small Letter B with top bar",
	"0184": "Latin Capital Letter Tone Six",
	"0185": "Latin Small Letter Tone Six",
	"0186": "Latin Capital Letter Open O",
	"0187": "Latin Capital Letter C with hook",
	"0188": "Latin Small Letter C with hook",
	"0189": "Latin Capital Letter African D",
	"018A": "Latin Capital Letter D with hook",
	"018B": "Latin Capital Letter D with top bar",
	"018C": "Latin Small Letter D with top bar",
	"018D": "Latin Small Letter Turned Delta",
	"018E": "Latin Capital Letter Reversed E",
	"018F": "Latin Capital Letter Schwa",
	"0190": "Latin Capital Letter Open E",
	"0191": "Latin Capital Letter F with hook",
	"0192": "Latin Small Letter F with hook",
	"0193": "Latin Capital Letter G with hook",
	"0194": "Latin Capital Letter Gamma",
	"0195": "Latin Small Letter HV",
	"0196": "Latin Capital Letter Iota",
	"0197": "Latin Capital Letter I with stroke",
	"0198": "Latin Capital Letter K with hook",
	"0199": "Latin Small Letter K with hook",
	"019A": "Latin Small Letter L with bar",
	"019B": "Latin Small Letter Lambda with stroke",
	"019C": "Latin Capital Letter Turned M",
	"019D": "Latin Capital Letter N with left hook",
	"019E": "Latin Small Letter N with long right leg",
	"019F": "Latin Capital Letter O with middle tilde",
	"01A0": "Latin Capital Letter O with horn",
	"01A1": "Latin Small Letter O with horn",
	"01A2": "Latin Capital Letter OI (= Latin Capital Letter Gha)",
	"01A3": "Latin Small Letter OI (= Latin Small Letter Gha)",
	"01A4": "Latin Capital Letter P with hook",
	"01A5": "Latin Small Letter P with hook",
	"01A6": "Latin Letter YR",
	"01A7": "Latin Capital Letter Tone Two",
	"01A8": "Latin Small Letter Tone Two",
	"01A9": "Latin Capital Letter Esh",
	"01AA": "Latin Letter Reversed Esh Loop",
	"01AB": "Latin Small Letter T with palatal hook",
	"01AC": "Latin Capital Letter T with hook",
	"01AD": "Latin Small Letter T with hook",
	"01AE": "Latin Capital Letter T with retroflex hook",
	"01AF": "Latin Capital Letter U with horn",
	"01B0": "Latin Small Letter U with horn",
	"01B1": "Latin Capital Letter Upsilon",
	"01B2": "Latin Capital Letter V with hook",
	"01B3": "Latin Capital Letter Y with hook",
	"01B4": "Latin Small Letter Y with hook",
	"01B5": "Latin Capital Letter Z with stroke",
	"01B6": "Latin Small Letter Z with stroke",
	"01B7": "Latin Capital Letter Ezh",
	"01B8": "Latin Capital Letter Ezh reversed",
	"01B9": "Latin Small Letter Ezh reversed",
	"01BA": "Latin Small Letter Ezh with tail",
	"01BB": "Latin Letter Two with stroke",
	"01BC": "Latin Capital Letter Tone Five",
	"01BD": "Latin Small Letter Tone Five",
	"01BE": "Latin Letter Inverted Glottal Stop with stroke",
	"01BF": "Latin Letter Wynn",
	"01C0": "Latin Letter Dental Click",
	"01C1": "Latin Letter Lateral Click",
	"01C2": "Latin Letter Alveolar Click",
	"01C3": "Latin Letter Retroflex Click",
	"01C4": "Latin Capital Letter DZ with caron",
	"01C5": "Latin Capital Letter D with Small Letter Z with caron",
	"01C6": "Latin Small Letter DZ with caron",
	"01C7": "Latin Capital Letter LJ",
	"01C8": "Latin Capital Letter L with Small Letter J",
	"01C9": "Latin Small Letter LJ",
	"01CA": "Latin Capital Letter NJ",
	"01CB": "Latin Capital Letter N with Small Letter J",
	"01CC": "Latin Small Letter NJ",
	"01CD": "Latin Capital Letter A with caron",
	"01CE": "Latin Small Letter A with caron",
	"01CF": "Latin Capital Letter I with caron",
	"01D0": "Latin Small Letter I with caron",
	"01D1": "Latin Capital Letter O with caron",
	"01D2": "Latin Small Letter O with caron",
	"01D3": "Latin Capital Letter U with caron",
	"01D4": "Latin Small Letter U with caron",
	"01D5": "Latin Capital Letter U with diaeresis and macron",
	"01D6": "Latin Small Letter U with diaeresis and macron",
	"01D7": "Latin Capital Letter U with diaeresis and acute",
	"01D8": "Latin Small Letter U with diaeresis and acute",
	"01D9": "Latin Capital Letter U with diaeresis and caron",
	"01DA": "Latin Small Letter U with diaeresis and caron",
	"01DB": "Latin Capital Letter U with diaeresis and grave",
	"01DC": "Latin Small Letter U with diaeresis and grave",
	"01DD": "Latin Small Letter Turned E",
	"01DE": "Latin Capital Letter A with diaeresis and macron",
	"01DF": "Latin Small Letter A with diaeresis and macron",
	"01E0": "Latin Capital Letter A with dot above and macron",
	"01E1": "Latin Small Letter A with dot above and macron",
	"01E2": "Latin Capital Letter Æ with macron",
	"01E3": "Latin Small Letter Æ with macron",
	"01E4": "Latin Capital Letter G with stroke",
	"01E5": "Latin Small Letter G with stroke",
	"01E6": "Latin Capital Letter G with caron",
	"01E7": "Latin Small Letter G with caron",
	"01E8": "Latin Capital Letter K with caron",
	"01E9": "Latin Small Letter K with caron",
	"01EA": "Latin Capital Letter O with ogonek",
	"01EB": "Latin Small Letter O with ogonek",
	"01EC": "Latin Capital Letter O with ogonek and macron",
	"01ED": "Latin Small Letter O with ogonek and macron",
	"01EE": "Latin Capital Letter Ezh with caron",
	"01EF": "Latin Small Letter Ezh with caron",
	"01F0": "Latin Small Letter J with caron",
	"01F1": "Latin Capital Letter DZ",
	"01F2": "Latin Capital Letter D with Small Letter Z",
	"01F3": "Latin Small Letter DZ",
	"01F4": "Latin Capital Letter G with acute",
	"01F5": "Latin Small Letter G with acute",
	"01F6": "Latin Capital Letter Hwair",
	"01F7": "Latin Capital Letter Wynn",
	"01F8": "Latin Capital Letter N with grave",
	"01F9": "Latin Small Letter N with grave",
	"01FA": "Latin Capital Letter A with ring above and acute",
	"01FB": "Latin Small Letter A with ring above and acute",
	"01FC": "Latin Capital Letter Æ with acute",
	"01FD": "Latin Small Letter Æ with acute",
	"01FE": "Latin Capital Letter O with stroke and acute",
	"01FF": "Latin Small Letter O with stroke and acute",
	"0200": "Latin Capital Letter A with double grave",
	"0201": "Latin Small Letter A with double grave",
	"0202": "Latin Capital Letter A with inverted breve",
	"0203": "Latin Small Letter A with inverted breve",
	"0204": "Latin Capital Letter E with double grave",
	"0205": "Latin Small Letter E with double grave",
	"0206": "Latin Capital Letter E with inverted breve",
	"0207": "Latin Small Letter E with inverted breve",
	"0208": "Latin Capital Letter I with double grave",
	"0209": "Latin Small Letter I with double grave",
	"020A": "Latin Capital Letter I with inverted breve",
	"020B": "Latin Small Letter I with inverted breve",
	"020C": "Latin Capital Letter O with double grave",
	"020D": "Latin Small Letter O with double grave",
	"020E": "Latin Capital Letter O with inverted breve",
	"020F": "Latin Small Letter O with inverted breve",
	"0210": "Latin Capital Letter R with double grave",
	"0211": "Latin Small Letter R with double grave",
	"0212": "Latin Capital Letter R with inverted breve",
	"0213": "Latin Small Letter R with inverted breve",
	"0214": "Latin Capital Letter U with double grave",
	"0215": "Latin Small Letter U with double grave",
	"0216": "Latin Capital Letter U with inverted breve",
	"0217": "Latin Small Letter U with inverted breve",
	"0218": "Latin Capital Letter S with comma below",
	"0219": "Latin Small Letter S with comma below",
	"021A": "Latin Capital Letter T with comma below",
	"021B": "Latin Small Letter T with comma below",
	"021C": "Latin Capital Letter Yogh",
	"021D": "Latin Small Letter Yogh",
	"021E": "Latin Capital Letter H with caron",
	"021F": "Latin Small Letter H with caron",
	"0220": "Latin Capital Letter N with long right leg",
	"0221": "Latin Small Letter D with curl",
	"0222": "Latin Capital Letter OU",
	"0223": "Latin Small Letter OU",
	"0224": "Latin Capital Letter Z with hook",
	"0225": "Latin Small Letter Z with hook",
	"0226": "Latin Capital Letter A with dot above",
	"0227": "Latin Small Letter A with dot above",
	"0228": "Latin Capital Letter E with cedilla",
	"0229": "Latin Small Letter E with cedilla",
	"022A": "Latin Capital Letter O with diaeresis and macron",
	"022B": "Latin Small Letter O with diaeresis and macron",
	"022C": "Latin Capital Letter O with tilde and macron",
	"022D": "Latin Small Letter O with tilde and macron",
	"022E": "Latin Capital Letter O with dot above",
	"022F": "Latin Small Letter O with dot above",
	"0230": "Latin Capital Letter O with dot above and macron",
	"0231": "Latin Small Letter O with dot above and macron",
	"0232": "Latin Capital Letter Y with macron",
	"0233": "Latin Small Letter Y with macron",
	"0234": "Latin Small Letter L with curl",
	"0235": "Latin Small Letter N with curl",
	"0236": "Latin Small Letter T with curl",
	"0237": "Latin Small Letter Dotless J",
	"0238": "Latin Small Letter DB Digraph",
	"0239": "Latin Small Letter QP Digraph",
	"023A": "Latin Capital Letter A with stroke",
	"023B": "Latin Capital Letter C with stroke",
	"023C": "Latin Small Letter C with stroke",
	"023D": "Latin Capital Letter L with bar",
	"023E": "Latin Capital Letter T with diagonal stroke",
	"023F": "Latin Small Letter S with swash tail",
	"0240": "Latin Small Letter Z with swash tail",
	"0241": "Latin Capital Letter Glottal Stop",
	"0242": "Latin Small Letter Glottal Stop",
	"0243": "Latin Capital Letter B with stroke",
	"0244": "Latin Capital Letter U bar",
	"0245": "Latin Capital Letter Turned V",
	"0246": "Latin Capital Letter E with stroke",
	"0247": "Latin Small Letter E with stroke",
	"0248": "Latin Capital Letter J with stroke",
	"0249": "Latin Small Letter J with stroke",
	"024A": "Latin Capital Letter Q with hook tail",
	"024B": "Latin Small Letter Q with hook tail",
	"024C": "Latin Capital Letter R with stroke",
	"024D": "Latin Small Letter R with stroke",
	"024E": "Latin Capital Letter Y with stroke",
	"024F": "Latin Small Letter Y with stroke"
};